### ISSUE TITLE
Add Object to array

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/parse-php-sdk#101]
Hello, I'm trying to add a file to Array Object in this  way : 
```
try {

            $file = ParseFile::createFromFile(Input::file('file'), Input::file('file')->getClientOriginalName());
            $file->save();

            $query = new ParseQuery("Devices");
            $obj = $query->get($id);
            $obj->addUnique("images", $file);
            $obj->save();

            return Response::json(array(
                'success' => true,
                'imageUrl' => $file->getURL()
            ));

        } catch (ParseException $ex) {
            return Response::json(array(
                'success' => false,
                'error' =>  $ex->getMessage()
            ));
        }
```
But I'm getting always : **AddUniqueOperation requires an array.** or **AddOperation requires an array.** for add function.
This is my object In parse It's array 
![capture d ecran 2015-05-06 a 10 43 57](https://cloud.githubusercontent.com/assets/1204608/7491029/49154dec-f3dd-11e4-808b-c4dd75296184.png)

**Comment by aruvalcaba** [comment]
Try doing this array($file)

**Comment by chlebta** [comment]
thank's it solved my issue. and how to remove this object from array ?

**Comment by mauriciord** [comment]
Did you find a way to remove ?
