### ISSUE TITLE
Can't set up static site with few PHP files

### ISSUE THREAD

**Issue by chamini2** [ParsePlatform/parse-php-sdk#103]
Hello, I want to set up a static website with parse, but I have a few PHP files that send emails, when I tried the static installation, the PHP files wouldn't work, so I'm trying to set it up with this.

In the README of the repository, it says: 
> Run "composer install" to download the SDK and set up the autoloader, and then require it from your PHP script:
> `require 'vendor/autoload.php';`

What PHP script is that supposed to be? Is there a sample app of how to use this framework so I can learn from it?

My current file directories look like this:

    .
    ├── cloud
    │   └── main.js
    ├── composer
    ├── composer.json
    ├── composer.lock
    ├── config
    │   └── global.json
    ├── public
    │   ├── confirmation.html
    │   ├── contact.php
    │   ├── contactsettings.php
    │   ├── css
    │   ├── experiencias
    │   ├── fonts
    │   ├── img
    │   ├── index.html
    │   ├── js
    │   ├── redirect.html
    │   ├── subscribe.php
    │   └── thanks.html
    └── vendor
        ├── autoload.php
        ├── composer
        └── parse

**Comment by gfosco** [comment]
Parse Hosting does not support PHP hosting.  You'll need to host the site elsewhere to run PHP code.

**Comment by chamini2** [comment]
And what about Wordpress?

**Comment by gfosco** [comment]
Parse Hosting also does not support hosting Wordpress installations.  Wordpress can be hosted elsewhere and while there's no first-party wordpress plugin, they do exist.

**Comment by cristiana214** [comment]
how to enable php google plus parse login?
