### ISSUE TITLE
Support for PHP 5.5 \DateTimeImmutable

### ISSUE THREAD

**Issue by matts2cant** [ParsePlatform/parse-php-sdk#104]
The library doesn't currently support PHP 5.5's new DateTimeImmutable objects to be passed inside queries. It returns the exception below:

```
  [Exception]
  Invalid type encountered.

Exception trace:
 () at /dev/vendor/parse/php-sdk/src/Parse/ParseClient.php:142
 Parse\ParseClient::_encode() at /dev/vendor/parse/php-sdk/src/Parse/ParseQuery.php:126
 Parse\ParseQuery->addCondition() at /dev/parse/php-sdk/src/Parse/ParseQuery.php:188
```

**Comment by gfosco** [comment]
Interested in submitting a PR?  If not, will try to get to it soon.

**Comment by matts2cant** [comment]
I'll be happy to submit one if I find the time ! I'll get back to you if I do :)

**Comment by gfosco** [comment]
Added in #122.  Test it out and let me know if you have any issues.

Thanks
