### ISSUE TITLE
I can't read values from the database written by another app user

### ISSUE THREAD

**Issue by alvarols** [ParsePlatform/parse-php-sdk#105]
I am developing an App with some people, the problem is that I can parse only the values I've written on the database. ¿What can I do?

**Comment by gfosco** [comment]
This is based on the ACLs for the object.  How are you securing them?  Please see the security guide inside any of our docs: i.e. https://parse.com/docs/android/guide#security

**Comment by alvarols** [comment]
I put this and i still have the same problem

	$acl = new ParseACL();
	$acl->setPublicReadAccess(true);
	$acl->setPublicWriteAccess(true);

**Comment by cristiana214** [comment]
check the class you created ,the ACL should look like this and you should be able retrieve it even if another users content
![capture](https://cloud.githubusercontent.com/assets/5396875/7764690/ed7136e8-0009-11e5-9d9a-1991eda2ca2a.PNG)
