### ISSUE TITLE
how can i do a join between two classes with parse PHP SDK?

### ISSUE THREAD

**Issue by alvarols** [ParsePlatform/parse-php-sdk#106]
I need to know how can I do a join beacuse the Parse guide is incomplete: https://parse.com/docs/php/guide#relations-using-join-tables

The problem is that we are some people from different accounts using an App and I can't read the data that other acount put on the database. I imagine that this could be done doing a Join between the users table and the custom table.

**Comment by gfosco** [comment]
This is more of a Parse question and not specific to the SDK.  I'd direct you towards parse.com/help where you'll find the link to the Google group to discuss this topic with the community.  Our guides on relations are also useful here.  Parse is a no-sql database and doesn't support the traditional concept of joins that might be familiar to a sql user.  Thanks.
