### ISSUE TITLE
need url for descending order !

### ISSUE THREAD

**Issue by vinita90** [ParsePlatform/parse-php-sdk#107]
hi all,

i am using parse url to fetch data, but i need my data in descending order.
My url to fetch data is : https://api.parse.com/1/classes/myclass?order=-starCount&limit=1 ..

**Comment by cristiana214** [comment]
$order = urlencode('order=-starCount');
$limit = urlencode('limit=100');
		$url = 'https://api.parse.com/1/classes/myclass?'.$order.'&'.$limit;    

for me it is working, don't limit it to 1 you won't see the difference

**Comment by vinita90** [comment]
Thanks cristiana214  !!! 

It is also working for me.
