### ISSUE TITLE
not getting all that fields from parse

### ISSUE THREAD

**Issue by vinita90** [ParsePlatform/parse-php-sdk#108]
i wrote this 
$url='https://api.parse.com/1/classname/'.$userid;

but not getting all the data from my class. How can i get all the columns from Class?

**Comment by cristiana214** [comment]
like what kind of field?

**Comment by gfosco** [comment]
Why not use ParseQuery?  You'll get all the fields for that object if you're logged in as that user.

Also, just because a class has certain columns, does not mean every object does.

**Comment by vinita90** [comment]
that is how i wrote my code to find all columns but.. i am not able to convert data in json.

<?php
require 'autoload.php';

 require 'src\Parse\ParseClient.php';
 require 'src\Parse\ParseObject.php';
 require 'src\Parse\ParseQuery.php';

 Parse\ParseClient::initialize('mykey','mykey', 'mykey');

 try{
 $query = new Parse\ParseQuery("videoListTable");
$query->descending("-starCount");
$query->limit('1');
$results = $query->find();
print_r($results);
//$result=json_decode($results);

// echo "Successfully retrieved " . count($results) . " scores.";
 } catch (Exception $e){
    echo $e->getMessage();
 }
?>

**Comment by cristiana214** [comment]
$query = new ParseQuery("classname");
		$result = $query->find();
		foreach($result as $row){ 
		echo $row->field1;
		echo $row->field2;
		echo $row->field3;
			}

Don't limit to 1 when you're ordering

**Comment by vinita90** [comment]
i got my record..thanks once again.
