### ISSUE TITLE
ParseObject::destroyAllI() - Requires ordered numerical indexes.

### ISSUE THREAD

**Issue by awgeorge** [ParsePlatform/parse-php-sdk#110]
I have an issue whereby after removing values from an array that I do not wish to delete, using array_diff - I am left with an array with the indexes out of sync. EG: `([4] => OBJECT, [7] => OBJECT)`

This causes an `undefined index` issue which leads to a fatal error.

    Notice: Undefined offset: 0 in /Users/Shared/Sites/parse/vendor/parse/php-sdk/src/Parse/ParseObject.php on line 766
    Fatal error: Call to a member function getClassName() on a non-object in /Users/Shared/Sites/parse/vendor/parse/php-sdk/src/Parse/ParseObject.php on line 791

The array can be normalised using `array_values` or potentially a rework of the processed while loop will fix the issue. I don't think you should assume the array will have keys starting at index 0.

Cheers.

**Comment by gfosco** [comment]
Updated in #121 Thanks for the heads up!

**Comment by awgeorge** [comment]
Cheers for your help.
