### ISSUE TITLE
ParseSDK is very slow

### ISSUE THREAD

**Issue by kiettran** [ParsePlatform/parse-php-sdk#111]
Hi there,

First of all, a great job on the ParseSDK. I have been working with the ParseSDK for a quite while now.
But for some reason the ParseSDK loads the amount of data very slow.

For example:
I am trying to load 9 items which contains 6 fields, a pointer to an user, a parse file, a pointer to a category, a title, a description and a counter of total amount of photos that are related to the item. Besides loading the items, I am using the count method to count the amount of results to create a pagination function. To do this all, it takes at least 30 seconds to load everything.

Are there any issues with the count method of parse query?

**Comment by gfosco** [comment]
Be sure to check the caveats here: https://parse.com/docs/php/guide#queries-counting-objects

Counts are not recommended, and will not be accurate for large classes.  While doing this, you're also making an extra network round trip.  

I've not had slow-ness such as you're describing, at all, so I suspect this has something to do with your environment and/or network.  It's a simple rest api interface, and is quite fast.
