### ISSUE TITLE
decoded error throwing improperly formatted exception

### ISSUE THREAD

**Issue by flound1129** [ParsePlatform/parse-php-sdk#113]
For some reason the response I'm getting from Parse includes the following:

     ["error"]=> array(0) { } 

This appears to trigger code in ParseClient.php (lines 293-296) to throw an exception, however the exception is thrown with incorrect parameters resulting in a PHP error:

PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /var/www/zapchain/public/autoload/Parse/ParseClient.php on line 297

**Comment by flound1129** [comment]
After further research, this appears to be happening due to a problem with a pointer in the User object pointing to a null object (doesn't exist in target class).

**Comment by flound1129** [comment]
After further further research, this does not appear to be happening due to a null pointer, it's actually happening because somehow a field called "error" was added to our class, and was not set.

**Comment by gfosco** [comment]
Interesting... glad you figured it out.

**Comment by flound1129** [comment]
Isn't it possible that someone could add a field called "error" somewhere though for a legitimate reason?  It doesn't appear to be a reserved word in Parse.

Would it be possible to distinguish this from an actual error?

**Comment by awgeorge** [comment]
@flound1129 I accidentally did this too by using `->save({error:function(){}})` and not `->save(null, {error:function(){}})`. Its quite simple to get stuck on this.
