### ISSUE TITLE
Implement `__isset` on ParseObject

### ISSUE THREAD

**Issue by awgeorge** [ParsePlatform/parse-php-sdk#115]
An implementation similar to:

     public function __isset($key){
		return $this->has($key);
     }

Would go a long way as your using `__get`.

**Comment by gfosco** [comment]
Interested in submitting a PR?

**Comment by awgeorge** [comment]
I very much would love too. But my Facebook account has been blocked and the functionality to get my friends to supply codes (`guardian.php`) looks like it fatal errors. Catch 22 because I can't file a bug report. HAHA. Don't suppose you know anybody in that department.

I digress, presently I cannot sign the  Contributor License Agreement.

**Comment by gfosco** [comment]
Ok, sorry about that...  Implemented in #120

**Comment by awgeorge** [comment]
(Y)
