### ISSUE TITLE
Adding new user to role

### ISSUE THREAD

**Issue by darkainsoul** [ParsePlatform/parse-php-sdk#116]
Hello i'm trying to add a new user to an existing role, the code don't send me any error, but don't add the user to the role. This is my code.
       
            $newObject->signUp();            
            $query = new ParseQuery('_Role');  
            $query->equalTo('name', 'a_'.$dataLinkPS);
            $role = $query->first();
            $role->getUsers()->add($newObject);
            $role->save();

**Comment by raffe90** [comment]
Did you check whether you need to use the MasterKey for this? 


$user->signUp();
$query = new ParseQuery('_Role');
$adminRole = new ParseRole();
$adminRole = $query->equalTo("name", "Administrator")->first(true);
$adminRole->getUsers()->add($user);
$adminRole->save(true);

**Comment by darkainsoul** [comment]
I found the problem, happens when the signup was completed and the current user is the new one and it doesn't has the same privileges that the initial user and this is the solution that i thought.

            $session = ParseSession::getCurrentSession();         
            $sessionToken = $session->getSessionToken();        
            $newObject->signUp();            
            $user = ParseUser::become($sessionToken);  

            $query = new ParseQuery('_Role');  
            $query->equalTo('name', 'a_'.$dataLinkPS);
            $role = $query->first();
            $role->getUsers()->add($newObject);
            $role->save();
