### ISSUE TITLE
Todo: Add Twitter login helper.

### ISSUE THREAD

**Issue by zEmily** [ParsePlatform/parse-php-sdk#117]
Hello, now I need my customers login with twitter then add them as parse users.Because there is no function I can use as twitter logining in ParseUser.php, so I write one: 

``` php
  public static function logInWithTwitter($id, $access_token, $expiration_date = null)
    {
        if (!$id) {
            throw new ParseException("Cannot log in twitter user without an id.");
        }
        if (!$access_token) {
            throw new ParseException(
                "Cannot log in twitter user without an access token."
            );
        }
        if (!$expiration_date) {
            $expiration_date = new \DateTime();
            $expiration_date->setTimestamp(time() + 86400 * 60);
        }
        $data = json_encode(['authData' =>
            ["twitter" => [
                "id" => $id, "access_token" => $access_token,
                "expiration_date" => ParseClient::getProperDateFormat($expiration_date)
            ]]
        ]);
        $result = ParseClient::_request("POST", "/1/users", "", $data);
        $user = new ParseUser();
        $user->_mergeAfterFetch($result);
        $user->handleSaveResult(true);
        ParseClient::getStorage()->set("user", $user);
        return $user;
    }
```

 But when I finished login with twitter, error occurs: `Code : 251 Message:Twitter credential verification failed.`.  I try to look for solutions, but all I found are things about apps platform problems, and they can fix if by setting  consumerKey and consumerSecret in TWSignedRequest. But I don't know whether I need to set twitter  consumerKey and consumerSecret, if I need to do this ,where should I set?

**Comment by zEmily** [comment]
Right now I add customer key to parse settings, but the error also occurs .

**Comment by sherizan** [comment]
I'm doing the longer method. Sign in via Facebook/Twitter, get his session fb, redirect to a new page, set password and set as a new user on Parse.

**Comment by zEmily** [comment]
@sherizan  I have found the right way to add twitter login user  as parse user. You can check this [https://parse.com/docs/rest/guide/#users-signup](https://parse.com/docs/rest/guide/#users-signup) and search for twitter, you'll see this:
```php
{
  "twitter": {
    "id": "user's Twitter id number as a string",
    "screen_name": "user's Twitter screen name",
    "consumer_key": "your application's consumer key",
    "consumer_secret": "your application's consumer secret",
    "auth_token": "an authorized Twitter token for the user with your application",
    "auth_token_secret": "the secret associated with the auth_token"
  }
}
```
and it works!

**Comment by gfosco** [comment]
Glad you figured out a way to do it using _request :) I'll leave this open though, because we should add a native method as we did for Facebook login.

**Comment by RaedsLab** [comment]
+1

**Comment by murnieza** [comment]
Any news on this one?

**Comment by talkaboutdesign** [comment]
Anyone working on this?

**Comment by talkaboutdesign** [comment]
Would be awesome if you can do this as part of the framework.

**Comment by RaedsLab** [comment]
@talkaboutdesign With everything going on with Parse, I wouldn't expect any updates.

**Comment by montymxb** [comment]
Anyone still interested in this? I imagine we'll be putting this in at some point this year given that support for this (and many more alt logins) has been setup on Parse Server's end. I'm on the project as a maintainer so we can keep things moving along here after Parse shuts down.

**Comment by vferdiansyah** [comment]
Just submitted a PR #297 for this. Could you help review it @montymxb?

**Comment by montymxb** [comment]
A twitter login helper has now been added to the sdk. In addition general purpose login/linker methods have been setup in `ParseUser`, this will allow us to add further 3rd party auths as needed. 

If there's a desire to add any additional auths be sure to open up an issue or a PR with the relevant additions and we'll take a look. You can find all of the supported auth options for parse server [here](https://github.com/ParsePlatform/parse-server/tree/master/src/Adapters/Auth). Among them there are some auths such as **github**, **google**, **instragram**, **linkedin**, **spotify** and more. 

We'll probably look into adding these and more as time goes just for good measure, but be sure to let us know anyone wants to have these integrated sooner.

**Comment by flovilmart** [comment]
Awesome! I'm not sure you need to integrate them all now, as the server should be able to understand requests as long as the auth adapter is configured correctly on the other side.

**Comment by montymxb** [comment]
@flovilmart we'll probably add them as demand requires, we should be good for now though. If anything I'm curious how the other sdks are keeping up with these new integrations. I also took the liberty of updating that last comment I left with some more details in regards to using 3rd party auth.

**Comment by flovilmart** [comment]
>  how the other sdks are keeping up with these new integrations

we technically still need to make those methods public in the JS SDK, but the mechanisms are open on iOS.
