### ISSUE TITLE
`ParseObject::getRelation` add $class parameter

### ISSUE THREAD

**Issue by awgeorge** [ParsePlatform/parse-php-sdk#126]
I may be misusing `getRelation` but if you update to this:

    public function getRelation($key, $class = null)
    {
        $relation = new ParseRelation($this, $key, $class);
    ....

Then you can get relations without fetching the parent object. Presumably this saves API calls.

    $teams =  (new ParseObject("Club", "ObFp5S29xm"))->getRelation("teams", "Team")->getQuery();

**Comment by gfosco** [comment]
This is a much more elegant solution than the method used by our other client SDKs... Would you be willing to send in a PR with this (and support both scenarios) ?

**Comment by gfosco** [comment]
Merged in #175.  Thanks :+1:

**Comment by awgeorge** [comment]
Awesome. Sorry for not patching, been really busy at work. Haven't had the chance to play with cool stuff :(
