### ISSUE TITLE
_encode() for ParseObject

### ISSUE THREAD

**Issue by aruvalcaba** [ParsePlatform/parse-php-sdk#13]
Hello I think the _encode() for ParseObject is not implemented correctly.

_encode() should not json_encode at all (Like the ParseGeoPoint encode method). If nested arrays are encoded (due to recursion) then encoding the top level array will cause a heap of issues when parsing the final JSON using existing JSON parsers. 

The encode should really be a toArray() method, where the result can be passed to a json_encode().
      
Line 790 and 795 should check if $value and $item are either a instanceof ParseObject or ParseGeoPoint. Since ParseGeoPoint is not being checked, then it will never be encoded.

I have made changes to my application as necessary, but would like to hear discussion. Hope this is clear.

**Comment by varunjoshi12** [comment]
Hi please can any one help me  i have to get the private object id in php from pass result result like this 

Array ( [0] => Parse\ParseObject Object ( [serverData:protected] => Array ( [Public] => 1 [SavedToProfile] => [deviceToken] => 20a584af3271d5fd9dc30ab282a68e3c4145bc9ee1ba4d617c9bd8aa029e2c65 [starCount] => 200 [userid] => Parse\ParseUser Object ( [_sessionToken:protected] => [serverData:protected] => Array ( ) [operationSet:protected] => Array ( ) [estimatedData:Parse\ParseObject:private] => Array ( ) [dataAvailability:Parse\ParseObject:private] => Array ( ) [className:Parse\ParseObject:private] => _User [objectId:Parse\ParseObject:private] => Gi0CnYzmAs [createdAt:Parse\ParseObject:private] => [updatedAt:Parse\ParseObject:private] => [hasBeenFetched:Parse\ParseObject:private] => ) [video] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-00e43821-92a3-4e3e-b63e-e5624f0025d1-video.mov [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-00e43821-92a3-4e3e-b63e-e5624f0025d1-video.mov [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoDescription] => Testing recorded video [videoThumbnil] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-75b26004-4611-4208-b678-4929f6ed5574-img [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-75b26004-4611-4208-b678-4929f6ed5574-img [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoTitle] => recording [videoTotalDuretion] => 39.15 [videoUploadedOnMonthAndYear] => April 2015 ) [operationSet:protected] => Array ( ) [estimatedData:Parse\ParseObject:private] => Array ( [Public] => 1 [SavedToProfile] => [deviceToken] => 20a584af3271d5fd9dc30ab282a68e3c4145bc9ee1ba4d617c9bd8aa029e2c65 [starCount] => 200 [userid] => Parse\ParseUser Object ( [_sessionToken:protected] => [serverData:protected] => Array ( ) [operationSet:protected] => Array ( ) [estimatedData:Parse\ParseObject:private] => Array ( ) [dataAvailability:Parse\ParseObject:private] => Array ( ) [className:Parse\ParseObject:private] => _User [objectId:Parse\ParseObject:private] => Gi0CnYzmAs [createdAt:Parse\ParseObject:private] => [updatedAt:Parse\ParseObject:private] => [hasBeenFetched:Parse\ParseObject:private] => ) [video] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-00e43821-92a3-4e3e-b63e-e5624f0025d1-video.mov [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-00e43821-92a3-4e3e-b63e-e5624f0025d1-video.mov [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoDescription] => Testing recorded video [videoThumbnil] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-75b26004-4611-4208-b678-4929f6ed5574-img [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-75b26004-4611-4208-b678-4929f6ed5574-img [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoTitle] => recording [videoTotalDuretion] => 39.15 [videoUploadedOnMonthAndYear] => April 2015 ) [dataAvailability:Parse\ParseObject:private] => Array ( [Public] => 1 [SavedToProfile] => 1 [deviceToken] => 1 [starCount] => 1 [userid] => 1 [video] => 1 [videoDescription] => 1 [videoThumbnil] => 1 [videoTitle] => 1 [videoTotalDuretion] => 1 [videoUploadedOnMonthAndYear] => 1 ) [className:Parse\ParseObject:private] => videoListTable [objectId:Parse\ParseObject:private] => r1E3122aA0 [createdAt:Parse\ParseObject:private] => DateTime Object ( [date] => 2015-04-16 12:13:51 [timezone_type] => 2 [timezone] => Z ) [updatedAt:Parse\ParseObject:private] => DateTime Object ( [date] => 2015-05-29 11:53:09 [timezone_type] => 2 [timezone] => Z ) [hasBeenFetched:Parse\ParseObject:private] => 1 ) )

**Comment by varunjoshi12** [comment]
hi i have achieve this by using parse docs
$query = new ParseQuery("GameScore");

$results = $query->find();
for ($i = 0; $i < count($results); $i++) { 
  $object = $results[$i];
  echo "objectid  :".$object->getObjectId();
  echo ",playername  :" .$object->get('playerName');
  echo ",score  :".$object->get('score');
}

**Comment by gfosco** [comment]
Going to close this for now... coming future SDK updates should see a change in this area.
