### ISSUE TITLE
Bad Request when querying using containedIn with more than 72 objects in array

### ISSUE THREAD

**Issue by rossrossp** [ParsePlatform/parse-php-sdk#132]
I am querying for a list of records of object X created by person A.
Using the results of that query, I am querying for a list of Y objects, where one of the columns is a pointer to object X. So I am using containedIn->("X", listOfXObjects)

This query works fine until my first query returns over 71 results. If I limit the query to 71 it works fine, or if I change one of the objects to belong to a different user so that the first query returns 71 results, it works fine.

However, if I do not take these measures, I get a Bad Request (-1) error.

Can you provide any guidance?

Thanks.

**Comment by gfosco** [comment]
Can you create a CURL call to reproduce this behavior, and email it to me at fjm@fb.com ? If not, provide a php repro for it.  Thanks.

**Comment by gfosco** [comment]
If you emailed me, please try again.  Closing this for now.
