### ISSUE TITLE
Getting Data from Pointer

### ISSUE THREAD

**Issue by jakeols** [ParsePlatform/parse-php-sdk#134]
I'm having a problem getting data from a pointer column with includeKey(). I'm getting the error:

    Call to a member function get() on a non-object

My code is:

    $query = new ParseQuery("SignoutDestination");
       $query->includeKey("User");
       // Limit what could be a lot of points.
       $query->limit(100);
       // Final array of objects
       $signoutdestinations = $query->find();

       foreach($signoutdestinations as $obj){
         echo $obj->get("User")->get("objectId");
       }

Has there been a change in the SDK or anything that could be causing this? I reviewed the previously open pull request regarding this issue, but it didn't solve my problem.

**Comment by RaedsLab** [comment]
if you `var_dump($obj->get("User"))`, what does it show ?

**Comment by jakeols** [comment]
See attached, it returns the data like expected...

![screen shot 2015-08-03 at 8 25 34 ptm](https://cloud.githubusercontent.com/assets/3232346/9050657/31cda508-3a1e-11e5-9ab9-eb1f705f2a3e.png)

**Comment by gfosco** [comment]
it seems like there is a lot more in that screenshot than just the output of one object...  You're doing something wrong here, and you should be checking $obj->get("User") before you attempt to access it.  Check it's type, etc.. It is obviously NOT a ParseObject because if it was, it wouldn't give you that error.

**Comment by jakeols** [comment]
I have checked it. As you can see below,  $obj->get("User")->get('username') actually returns what's needed, but still with an error for some reason. 

![screen shot 2015-08-06 at 4 39 06 ptm](https://cloud.githubusercontent.com/assets/3232346/9122851/b26e9f72-3c59-11e5-9ca9-9b2e53e3dc3b.png)

**Comment by jakeols** [comment]
"jakeolsjakeols..." is exactly the values that I am trying to access

**Comment by gfosco** [comment]
Then one or more rows in your SignoutDestinations class doesn't have a pointer object in the User column.  Find it in the data browser.  You can't assume they all have a pointer, so you need to check this in each iteration of this loop.  something like `if ($obj->get("User")) { ...` or `if ($obj->get("User") instanceof ParseUser) { ...`

**Comment by jakeols** [comment]
Thank you!!!

I had 2 records at the end that randomly didn't have a pointer. Solved my problem.
