### ISSUE TITLE
Sessions not unserializing correctly 

### ISSUE THREAD

**Issue by nick2687** [ParsePlatform/parse-php-sdk#136]
Hi,

I'm trying to use the PHP SDK to pull some data into an existing modx (php cms / framework) website however i'm having an issue with maintaining sessions. 

The issue seems to be similar that I have found on here and stackoverflow where the solution was to  call `session_start()` after using `autoload.php` and the `use` statements, e.g

The problem i'm having is that Modx as a framework calls session_start automatically and well before any additional php files are run (so it gets called before the autoload.php file is called). This leads to the following error showing up in my server logs:

```
[11-Aug-2015 22:54:03 America/Chicago] PHP Fatal error:  Cannot use object of type __PHP_Incomplete_Class as array in /paas/c1445/www/core/components/composerx/vendor/parse/php-sdk/src/Parse/ParseUser.php on line 339
```

Is there anyway other option for unserializing the session if I cannot manually call session_start() after the autoload?

Thanks for your help in advance!

**Comment by nick2687** [comment]
So the below seems to be working but i'm not sure if there are any issues with doing it this way... 

Maybe you can comment as to if there is any kind of security or other issue with doing the following:

When I login I am json encoding the user session:
```

try { 
  $user = ParseUser::logIn('nick2687', 'ouellon11');
$user_json = json_encode($user);
$_SESSION['user'] = $user_json; 

} catch (ParseException $ex) {

}

```

Then on every any other request I am doing the reverse before checking for the user session
```
$user_json = $_SESSION['user'];
$user = json_decode($user_json);

$user = ParseUser::getCurrentUser();
if ($user) {
    // do stuff with the user
} else {
    // show the signup or login page
}
```

**Comment by nick2687** [comment]
I resolved this by modifying the modsessionhandler.class.php file  to include the following code at the top of it so that it requires the autoload and ParseUser class prior to session_start().

Just wanted to update you incase anyone else comes along looking for a solution to the similar. Thanks

```
<?php
require_once (MODX_CORE_PATH . 'components/composerx/vendor/parse/php-sdk/autoload.php');
use Parse\ParseClient;
use Parse\ParseUser;
```

**Comment by gfosco** [comment]
:+1:
