### ISSUE TITLE
how to update a pointer in a table

### ISSUE THREAD

**Issue by edwinbastiaens** [ParsePlatform/parse-php-sdk#138]
I am tyring to update a pointer-column of an object. In the example CarOwnerId is a pointer-column to a User.  $user holds the objectid of the User in a string.

$qry = new ParseQuery("Car");
$obj = $qry->get( $carid);
$obj->set("CarOwnerId", $userid );
$obj->save();

This results in Fatal error: Uncaught exception 'Parse\ParseException' with message 'invalid type for key CarOwnerId expected *_User, but got string.  
I guess I should somehow provide a *_User - like parameter in stead of a simple string.  But how should I then do that?

**Comment by gfosco** [comment]
Correct, you should be putting the User object, not just the objectId.  If all you have is the objectId, it's pretty easy to create a pointer object:

```
$user = ParseObject::create("_User", $userid, true);
```
