### ISSUE TITLE
error 251: The supplied Facebook session token is expired or invalid.

### ISSUE THREAD

**Issue by piu-coder** [ParsePlatform/parse-php-sdk#139]
Hi All,

I am not able to login with facebook anymore and getting the error mentioned in title of issue. Following URL seems relevant but not sure how to fix it in php:

http://stackoverflow.com/questions/29010806/swift-the-supplied-facebook-session-token-is-expired-or-invalid

Any help would be appreciated.

**Comment by gfosco** [comment]
Have you verified that the token is valid via: https://developers.facebook.com/tools/debug/ ?

Please provide some code and any additional details you have.  Thanks.

**Comment by piu-coder** [comment]
I was using app token instead of user token, my bad. Thanks for the help. Closing the issue.
