### ISSUE TITLE
Not sure how ::SaveAll() works

### ISSUE THREAD

**Issue by piu-coder** [ParsePlatform/parse-php-sdk#140]
Hi All, 

I am trying to save multiple objects at once with ParseObject::saveAll(), but it is returning error invalid json or missing username password. Here is the code I am using:

	foreach($objectIds as $objectId ){
			if(isset($objectId['add'])){
				if(!in_array($objectId['add'],$checkDuplicate)){
					$parseUser = new ParseObject('_User', $objectId['add']);
					$parseUserFollower = new ParseObject('_User',ParseUser::getCurrentUser()->getObjectId() );
					$parseFollower = new ParseObject('UserFollower');
					$parseFollower->set('follower',$parseUserFollower);
					$parseFollower->set('followee',$parseUser);
					$parseFollower->set('isBlocked',false);
					//$parseFollower->set('ACL',json_encode(array('*' => array('read' => true), 'role:moderator' => array('write'=>true),$objectId['add'] => array('write' => true),"role:admin" => array('write' => true), Yii::app()->session['userProfile']->objectId => array('write' => true))));
					$checkDuplicate[] = $objectId['add'];
					$addObjects[] = $parseFollower;
					
					//$parseBatch->setBatchRequest("POST",'UserFollower',Yii::app()->session['userProfile']->sessionToken, array('follower' => $parseBatch->dataType('pointer',array('_User',Yii::app()->session['userProfile']->objectId)), 'followee' => $parseBatch->dataType('pointer',array('_User',$objectId['add'])),'ACL' => array('*' => array('read' => true), 'role:moderator' => array('write'=>true),$objectId['add'] => array('write' => true),"role:admin" => array('write' => true), Yii::app()->session['userProfile']->objectId => array('write' => true)), 'isBlocked' => false));
				}
			}
			if(isset($objectId['remove'])){
				$parseInvite = new ParseObject('UserInvitation',$objectId['remove']);
				$removeObjects[] = $parseInvite;
			}
			
			//$parseBatch->setBatchRequest("DELETE",'UserInvitation/'.$objectId['remove'],Yii::app()->session['userProfile']->sessionToken);
		}
		try{
			
			ParseObject::saveAll($addObjects,true);
			ParseObject::destroyBatch($removeObjects,true);
			return true;
			
		}catch (ParseException $ex){
			
			echo $ex->getMessage(); echo $ex->getCode();exit;
		}	

Also not sure how destroyBatch is different from destroyAll. 
Thanks in advance.

**Comment by gfosco** [comment]
Try changing:
```
$parseUser = new ParseObject('_User', $objectId['add']);
```
To:
```
$parseUser = ParseObject::create("_User", $objectId['add'], true);
```
I believe it was seeing the user object as new/unsaved and trying to save it in the batch, which can't be done.
