### ISSUE TITLE
ParsePush with ParseQuery which contains ParseObject does not work

### ISSUE THREAD

**Issue by mikkokut** [ParsePlatform/parse-php-sdk#143]
Hi,
it seems that ParsePush does not encode ParseObjects if they are in ParseQuery. I got it working by adding ParseClient::_encode() to the line 64 in ParsePush.php.

Is this real issue or am I doing something wrong.

**Comment by gfosco** [comment]
That sounds like a real issue, surprised it hasn't come up before..  Would you like to submit a PR?

**Comment by gfosco** [comment]
Fixed by a recent commit.
