### ISSUE TITLE
get all records

### ISSUE THREAD

**Issue by sagar73** [ParsePlatform/parse-php-sdk#144]
i have more than lac's  of records.
because of limitation of 1000 records i can't get all together.
how can get using parseQuery.

**Comment by RaedsLab** [comment]
You can play with `order`, `limit` and `skip` parameters to get some paging to work.

**Comment by sagar73** [comment]
i have used all these parameters but there is limit of 10000 in skip function argument.will you please send me sample script. 


     On Wednesday, 2 September 2015 11:49 AM, Raed <notifications@github.com> wrote:
   

 You can play with order, limit and skip parameters to get some paging to work. —

**Comment by gfosco** [comment]
The best way is to order by objectId or createdAt, these are indexed fields... Pull with limit 1000 and then use greaterThan on that key from the last object to continue paging.

**Comment by sagar73** [comment]
i'm getting the error bellow while loading the data."Uncaught exception 'Parse\ParseException' with message 'transfer closed with outstanding read data remaining'"will you please help me... 


     On Friday, 4 September 2015 2:32 AM, Fosco Marotto <notifications@github.com> wrote:
   

 Closed #144.—
