### ISSUE TITLE
After login and redirect, ParseUser::getCurrentUser() gives null

### ISSUE THREAD

**Issue by piu-coder** [ParsePlatform/parse-php-sdk#145]
After logging in, I am not able to get the data of current user. I tried printing $_SESSION and got the following output:

Array ( [dae551591215d9e78a5c20b0d3966370__id] => cqHcmkt2Lv [dae551591215d9e78a5c20b0d3966370__name] => japrvni [dae551591215d9e78a5c20b0d3966370__states] => Array ( ) [parseData] => Array ( ) )

I am trying to implement API in YII framework. Any help would be appreciated.

**Comment by gfosco** [comment]
What does your login code look like?

**Comment by piu-coder** [comment]
Here is the code:

public function loginWithFacebook($id,$token){
		try{
			ParseUser::logInWithFacebook($id,$token);
			$currentUser = ParseUser::getCurrentUser();
			$objectId = $currentUser->getObjectId();
			$lastName = (isset($currentUser->lastName))? $currentUser->lastName: '';
			$model = new LoginForm;
			//$this->errorCode = UserIdentity::ERROR_NONE;
			$followees = $this->getFollowersOfLoggedInUser($objectId);
			
			$followeesList = json_encode(array($objectId => $followees));
			
			
			//Redirect to previous url
			return array('status' => 1,'returnUrl' => Yii::app()->user->returnUrl,'loggedInUser' => $currentUser->getObjectId(), 'firstName' => $currentUser->firstName, 'lastName' => $lastName, 'facebook' => 1, 'followee' => $followeesList );exit;
		}
		catch(ParseException $ex){
			echo $ex->getCode()." ".$ex->getMessage();exit;
		}
	}
