### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by juliangut** [ParsePlatform/parse-php-sdk#146]
I've looked for this on the tickets and found nothing

Why is API version specified in every _request method call instead of setting a parameter (or constant) in ParseClient? it's nonsense to write it down everywhere when it doesn't change at all

**Comment by gfosco** [comment]
Yeah, it does seem unnecessary, but it came about because not all requests were /1/, especially internally.  I'd review a PR that changed this.  Thanks.
