### ISSUE TITLE
deploying php code on Parse

### ISSUE THREAD

**Issue by anuagrawal7** [ParsePlatform/parse-php-sdk#150]
Hello,
I have created a web app using parse php sdk. i have build this app in php codeigniter framework with php sdk. Now I want to host my app on parse. Is it possible to host php files in parse. I have in total 8600 files in my app.
Can someone please tell me if deploying php code on parse is possible or not.

Thanks in advance

**Comment by luisbatista** [comment]
Isn't possible to host php files on parse hosting, only html+js (hosting have node.js), more info here: https://www.parse.com/docs/php/guide#hosting
