### ISSUE TITLE
Does not work on HHVM - DateTImeZone problems

### ISSUE THREAD

**Issue by fredemmott** [ParsePlatform/parse-php-sdk#151]
https://github.com/facebook/hhvm/issues/3637

Does not work (parse does this currently):

```
unserialize(serialize(new DateTime("2013-02-02T00:00:00Z")))
```

Works fine:

```
unserialize(serialize(new DateTime("2013-02-02T00:00:00 UTC")))
```

While this should be fixed in HHVM too, it would be good to change this in the Parse SDK because of the faster release cycle, and how much simpler it is to use HEAD of the SDK compared to doing a custom build of HHVM.

**Comment by gfosco** [comment]
The fix is not simple, and would be purely to work around a bug in HHVM..  Considering it has affected so few people, and will work once HHVM updates this scenario, we'll not change the behavior here.
