### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by juliangut** [ParsePlatform/parse-php-sdk#153]
Why classes start by ParseXxx when \Parse namespace is already being used?
If I end up having a name collision in my files ...
```php
use Parse\User as ParseUser;
```
What about changing that?

Is there a reason why there are static methods all over the place? What do you think on turning this into proper OOP (Open/close, SRP, Composition over inheritance, ...)?

**Comment by RaedsLab** [comment]
I agree that it is redundant but this avoids some confusion when dealing with Parse\User and MyApp\User ..

**Comment by juliangut** [comment]
@RaedsLab well, actually confusion gets removed using aliasing as in my example above

Lets say you use `Object`, `User`, `Role` and `Client` in your script, if you really have a name collision OR you just don't want to refactor the code, then aliasing allows you to only update the use statements and keep going the same way

```php
// From this
use Parse\ParseObject;
use Parse\ParseUser;
use Parse\ParseRole;
use Parse\ParseClient;

// To this
use Parse\Object as ParseObject;
use Parse\User as ParseUser;
use Parse\Role as ParseRole;
use Parse\Client as ParseClient;
```

Namespaces deprecate the former "technique" of _prefixes_ to avoid collisions, but in this library both techniques are mixed together

**Comment by gfosco** [comment]
I understand the sentiment, but I consider this a by-design decision from a year ago.  I'd like to see the SDK advance, but I don't think this is problematic enough to cause a huge breaking change on the next major version.  Thanks.
