### ISSUE TITLE
ParseFile save leading to a Empty server response error

### ISSUE THREAD

**Issue by dest4131** [ParsePlatform/parse-php-sdk#156]
Dear community,
I have a small php script that works on two hosts with PHP 5.4 (one shared, one debian), and does not work on a PHP 5.6 debian server.

    require "vendor/autoload.php";
    use Parse\ParseClient;
    use Parse\ParseUser;
    use Parse\ParseObject;
    use Parse\ParseQuery;
    use Parse\ParseException;
    use Parse\ParseFile;
    ParseClient::initialize("xxx", "xxx","");
    $user = ParseUser::logIn("user", "pass");
    $query = new ParseQuery("Subscription");
    $pSubscription = $query->get($subscriptionId);
    $file = ParseFile::createFromFile($invoiceFileName, $invoiceNumber . ".pdf");
    $file->save();

The script halts at the save() method and, after 20 seconds or so, I get a "Empty server response" error.
Does anybody have a clue about this situation?
note that I get a response (404 page actually) with curl https://api.parse.com/1/ and that the $invoiceFileName file has 777 permissions.

**Comment by gfosco** [comment]
Unclear what the issue would be here... Try to do some additional troubleshooting to see if there's a problem with $file, and re-open this if you find anything more.  Thanks.

**Comment by Lwdthe1** [comment]
I am getting a similar issue. Trying to query my database is halting and returning Empty Server response. This started happening after I added a new class to my database through the dashboard. After I removed it, my requests were back to normal and working again.... Why can't I add a new class to my database as I did without an error occurring?
