### ISSUE TITLE
Temporary SSL error / unknown ssl protocol

### ISSUE THREAD

**Issue by Scentyoo** [ParsePlatform/parse-php-sdk#157]
Unknown SSL protocol error in connection to api.parse.com:443

```
Parse\ParseException::__set_state(array( 'message' => 'Unknown SSL protocol error in connection to api.parse.com:443 ', 'string' => '', 'code' => 35, 'file' => '/vendor/parse/php-sdk/src/Parse/ParseClient.php', 'line' => 284, 'trace' => array ( 0 => array ( 'file' => '/vendor/parse/php-sdk/src/Parse/ParseQuery.php', 'line' => 346, 
```

the only option is to set 
```php
 curl_setopt($rest, CURLOPT_SSL_VERIFYPEER, false); 
```

but that isnt really recommended, right?

**Comment by ItsReddi** [comment]
same problem here

**Comment by RaedsLab** [comment]
If you're working on your local WAMP/XAMPP/LAMP/etc.. or anything pre-prod without a valid certificate you should use this as a temporary fix

**Comment by Scentyoo** [comment]
yes, but I'm concerned about my live-Server!

**Comment by RaedsLab** [comment]
If you have a valid SSL it should work no?

**Comment by gfosco** [comment]
Definitely, the workaround should only be used in testing scenarios, it would not be wise to disable peer validation in production.  Closing this, but open to suggestions.  Thanks.

**Comment by Scentyoo** [comment]
Why did you close this? The problem still exists... many times every day!

**Comment by izimodo** [comment]
Can confirm, this problem has been showing up a lot more in the recent days

**Comment by digitalturtle** [comment]
agreed, this issue should be reopened until a solution is found as it's affecting production sites which have valid SSL certificates and has been happening more often over the past 7 days.

**Comment by digitalturtle** [comment]
http://stackoverflow.com/a/16495053/4007992 seems to look quite promising and straightforward if it is indeed correct?

**Comment by ItsReddi** [comment]
any news about this? we are recieving this error more then 500 times per day... then it is okay agian for some hours.

**Comment by peldhose** [comment]
i think its the issue with certifi latest version so downgrading certifi may solve issue

pip uninstall -y certifi && pip install certifi==2015.04.28

                            or 

pip install requests[security]

**Comment by StellaPettre** [comment]
This issue should be reopened until a solution is found as it's affecting production sites which have valid SSL certificates and want to get the solution of it try [Solution Steps Chrome Err Ssl Protocol Error](https://notresponding.net/8-solution-steps-chrome-err_ssl_protocol_error/) which seriously works for you.
