### ISSUE TITLE
Duplicate Notification on Android Devices

### ISSUE THREAD

**Issue by hbabhishek** [ParsePlatform/parse-php-sdk#158]
Hello Parse Team,

We are sending push notification to Android users based on their Installation class Object Id. But some users are receiving duplicate notifications. 

We checked our server log and it shows that we have sent the notification only one time. 

I have attached the duplicate notification screenshot sent by user with this. 

![screenshot_2015-09-09-11-26-08](https://cloud.githubusercontent.com/assets/14979235/10282816/59661a70-6b9a-11e5-8b6e-4b14aafdc911.png)

I am using following PHP code to initiate parse push for android device user -
 
        function androidParseNotification($device_id = '', $message = 'hi', $extra = array()) {
               /*echo $device_id;
               echo $message;exit;*/
              $url = 'https://api.parse.com/1/push';
              $result = '';
              try {
                   if (empty($device_id)) {
                   throw new Exception("Device token not found..!");
                   }
            if(is_array($device_id))
            $device_id = implode(',', $device_id);
            $device_tokenArr = explode(',', $device_id);

            $APPLICATION_ID = $this->CI->config->item('PARSE_APPLICATION_ID');
            $REST_API_KEY = $this->CI->config->item('PARSE_REST_API_KEY');
            
            if (empty($REST_API_KEY) || empty($APPLICATION_ID)) {
                throw new Exception("Push notification Authorization key not found..!");
            }
            $payLoadArray = $extra;
            $payLoadArray['alert1'] = $message;
            $push_payload = json_encode(array(
                                           "where" => array(
                                        "objectId" => array('$in' => $device_tokenArr),
                                ),
                    "data" => $payLoadArray
            ));
            //pr($push_payload);
            if (!function_exists('curl_version')) {
                throw new Exception("CURL is not installed in this server..!");
            }

            // Open connection
            $rest = curl_init();
            if (!$rest) {
                throw new Exception("CURL intialization fails..!");
            }
            // Set the url, number of POST vars, POST data
            curl_setopt($rest,CURLOPT_URL,$url);
            curl_setopt($rest,CURLOPT_PORT,443);
            curl_setopt($rest,CURLOPT_POST,1);
            curl_setopt($rest,CURLOPT_POSTFIELDS,$push_payload);
            curl_setopt($rest, CURLOPT_RETURNTRANSFER, TRUE);
            curl_setopt($rest,CURLOPT_HTTPHEADER,
                    array("X-Parse-Application-Id: " . $APPLICATION_ID,
                            "X-Parse-REST-API-Key: " . $REST_API_KEY,
                            "Content-Type: application/json"));

            // Execute post
            $response = curl_exec($rest);
            //pr($rest);
            //pr($response);
            // Close connection
            curl_close($rest);
            //exit;
            if (!$response) {
                throw new Exception("CURL execution fails..!");
            }

            $success = 1;
            $message = "Push notification send successfully..!";
        } catch (Exception $e) {
            $success = 0;
            $message = $e->getMessage();
        }

        return $success;
    }

Let me know in case further details require.

**Comment by gfosco** [comment]
It's possible that you're not using GCM on the Android build?  This was an old issue, where development devices that have had an app installed & reinstalled could wind up getting double pushes.  If this is the case, you should upgrade to GCM and be sure to uninstall any trace of the app and any ParsePushService or PushService apps on the device.  Re-open if you have further insight.  Thanks.
