### ISSUE TITLE
Can't initialize the Parse

### ISSUE THREAD

**Issue by Ixilon** [ParsePlatform/parse-php-sdk#159]
Hello, Im getting the following error when trying to initialize :

"Fatal error: Class 'Parse\ParseUser' not found in /home/***/public_html/src/Parse/ParseClient.php on line 81"

<code>
<?php

define( 'PARSE_SDK_DIR', 'src/Parse/' );

require_once( 'autoload.php' );
 
use Parse\ParseClient;

use Parse\ParseObject;

use Parse\ParseQuery;

use Parse\ParseUser;
 
ParseClient::initialize('xxx', 'yyy', 'zzz');

</code>

Please advise how to fix it

<code>
/index.php

/src/Parse/ParseClient.php
</code>

**Comment by gfosco** [comment]
Unclear what the issue is here... Strongly encourage you to install it with composer, or just require the autoload file without defining PARSE_SDK_DIR.  Re-open if you have more insights.  Thanks.
