### ISSUE TITLE
Unable to remove key from Associative Array

### ISSUE THREAD

**Issue by nicklee1990** [ParsePlatform/parse-php-sdk#160]
When trying to remove a key from an associative array using the remove() method, if the last item in the array is removed, the following exception is thrown:

    'Parse\ParseException' with message 'invalid type for key 'providers', expected map, but got array'

called using the following code:

    $user->remove('providers', 'test'); 
    $user->save(); 

The following also fails

    $user->remove('providers', ['test']); 
    $user->save();

In the example given, the key on the ParseObject is 'providers' and it is a one dimensional associative array. It seems like the issue is being caused by the providers column being an associative array and removing the last key makes it an empty array which is interpreted as a regular indexed array.

**Comment by gfosco** [comment]
It sounds like "providers" is not an array but an object... so you can't use array commands.  Try taking the 'providers' value and removing the key locally and then .set'ing the new value of the providers key.  Re-open if you have any issues, thanks.
