### ISSUE TITLE
addUnique Failing

### ISSUE THREAD

**Issue by digitalturtle** [ParsePlatform/parse-php-sdk#166]
When trying to add a unique object to my an array on my ParseObject (a custom subclass), I am encountering the following error:

    local.ERROR: exception 'Parse\ParseException' with message 'Method 'PUT' to 'classes/_User/daagGtZJGd' not supported in batch operations.' in /vendor/parse/php-sdk/src/Parse/ParseClient.php:300

The lines code which is causing this error:

    $lead->increment('purchasers', 1);
    $lead->addUnique('purchasedBy', [$user]); //$user here is the ParseUser i.e. a pointer. 
    $lead->save(true);

Just for testing I tried separating the calls out: 

    // This succeeds
    $lead->increment('purchasers', 1);
    $lead->save(true);
    // This fails
    $lead->addUnique('purchasedBy', [$user]);
    $lead->save(true);

Any ideas? Have you seen this?

**Comment by digitalturtle** [comment]
I should note this exact code was working previously about a week or 2 ago

**Comment by digitalturtle** [comment]
ah actually it was because I had incremented my user model as well earlier in the class so the User object had been modified. However, SaveAll was not working either but i have just moved the statements round in the code and it is now working. i.e.

        $user->increment('purchases', 1);
        $lead->increment('purchasers', 1);
        $lead->addUnique('purchasedBy', [$user]);
        ParseObject::saveAll([$lead, $user], [true]);

failed. however the following works:

        $lead->addUnique('purchasedBy', [$user]);
        $lead->increment('purchasers', 1);
        $lead->save(true);
        $user->increment('purchases', 1);
        $user->save(true);

**Comment by digitalturtle** [comment]
reopening just in case there is actually an issue here

**Comment by gfosco** [comment]
Interesting... I don't think there is an issue here (at least not at the SDK level,) unless we could detect this..  Closing for now.  Thanks.
