### ISSUE TITLE
Targeted Push not working

### ISSUE THREAD

**Issue by ArifADS** [ParsePlatform/parse-php-sdk#167]
I used the PHP SDK for sending Push Notification last year and worked perfectly, but I updated the SDK and my code is not working this year, so i went back to the old version and seems to work great, I'm doing it like it says in the Docs.

My Code:

```PHP
$queryIOS = ParseInstallation::query();
$queryIOS->equalTo('start', true);
$queryIOS->containedIn("channels", [$t1,$t2,"dev"]);

ParsePush::send(array(
  "where" => $queryIOS,
  "data" => array(
       "alert" => $startString,
       "category" => "PbP2",
       "gameID" => $match{"id"}
  )
));
```

any problem seen?

**Comment by stoiev** [comment]
It seens a typo on 8e7d135. I faced it too.

**Comment by gfosco** [comment]
Good spot @stoiev !  Can you send in a PR to address it?

**Comment by sahanh** [comment]
What a mistake, please accept my PR.
