### ISSUE TITLE
Cannot resolve host

### ISSUE THREAD

**Issue by NielsKoole** [ParsePlatform/parse-php-sdk#168]
I get an error, cannot point it to my own code, so maybe there are issues with the host at the moment?

Fatal error: Uncaught exception 'Parse\ParseException' with message 'Couldn't resolve host 'api.parse.com'' in /_classes/vendor/parse/php-sdk/src/Parse/ParseClient.php:288 Stack trace: #0 /_classes/vendor/parse/php-sdk/src/Parse/ParseQuery.php(352): Parse\ParseClient::_request('GET', 'classes/Account...', NULL, NULL, false) #1 /_classes/M2P/M2PUser.php(78): Parse\ParseQuery->find() #2 /login.php(26): M2PUser->loginWithCredentials('....', '...') #3 {main} thrown in /...../_classes/vendor/parse/php-sdk/src/Parse/ParseClient.php on line 288

**Comment by gfosco** [comment]
Not likely... Check that your DNS is working and that you can resolve api.parse.com by other means (ping, dig, host, etc.)  Re-open if you have additional details, but this appears to be a problem with your environment.
