### ISSUE TITLE
Mocking Parse Rest API for Tests

### ISSUE THREAD

**Issue by sahanh** [ParsePlatform/parse-php-sdk#172]
I was wondering how viable is to mock the rest api of parse for sdk unit tests. https://github.com/Codeception/AspectMock might be a good option.

**Comment by gfosco** [comment]
It's useful, but it's a lot of work, and I really like integration tests.  If someone wanted to put in the effort, I'd be supportive and willing to accept, but it's pretty low-pri in my opinion.  Thanks.
