### ISSUE TITLE
PHP errors is save in parse file

### ISSUE THREAD

**Issue by christopherdev** [ParsePlatform/parse-php-sdk#174]
hi,

I am trying to upload an image to parse with PHP crop images, it does upload with PHP errors.
It can be viewed when you open the file.

**Comment by sahanh** [comment]
It would be helpful if you mention the errors and possibly some code to reproduce the error.

**Comment by christopherdev** [comment]
$filename = //image from a url
	$headers = get_headers($filename, 1);
	$content_type = $headers["Content-Type"];

       // Resample
	$image_p = imagecreatetruecolor($w, $h);

         $image = imagecreatefrompng($filename);
	  $content_type = 'image/png';
	  imagealphablending($image_p, false);
	  imagesavealpha($image_p,true);
	  $transparent = imagecolorallocatealpha($image_p, 255, 255, 255, 127);
	  imagefilledrectangle($image_p, 0, 0, $w, $h, $transparent);
	
	imagecopyresampled($image_p, $image, 0, 0, $x, $y, $w, $h, $w, $h);

	// Content type
	header('Content-type: ' . $content_type);
 	imagepng($image_p);
	

       the above is called 

	require 'vendor/autoload.php';
	use Parse\ParseClient;
	 
	ParseClient::initialize('xxx', 'yyy', 'zzz');

	use Parse\ParseObject;
	use Parse\ParseQuery;
	use Parse\ParseFile;

  	$file = ParseFile::createFromData( file_get_contents($url), 'test.png' ) );
	$file->save();

	$class = new ParseQuery("class");
	$class->equalTo("objectId",object_id)); 
	try {
      $res = $class->find();   
      for ($i = 0; $i < count($res); $i++) {
      	$object = $res[$i];
      	$object->set('image', $file);
		$object->save();
}

remove bits an pieces of the code, the idea is I am cropping an image and when it fails to render the image it will still upload to parse with the errors.

this is 1 of the warning/notices I got "$url is not a valid PNG file" when I open the file in parse 

note: not errors but warnings/notices

**Comment by gfosco** [comment]
Doesn't sound like this is related to the SDK, but in error checking on your image manipulation.  You should be able to detect that it failed to render, and not save it to Parse.
