### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by BTopbas** [ParsePlatform/parse-php-sdk#185]
Hi all devs;
This is not issue or bug report. I need to help for social login and parse. 
I use hybridauth class for social logins. (http://hybridauth.sourceforge.net/)
I successfully login and signup with this. But i cant define parseuser with login. Because i cant know user pass and i cant retrive pass.
How can i login without user password in php? 
http://hybridauth.sourceforge.net/userguide/HybridAuth_Sessions.html 
HybridAuth have sesssions and php sdk have $user = ParseUser::become("session-token-here"); i think i need to use this. But i cant figure out. Anyone here use social login?

**Comment by BTopbas** [comment]
Here is code http://pastebin.com/RbAph4px

**Comment by montymxb** [comment]
Going to close this as it has been awhile. If you're still interested in figuring this out you can checkout the [Parse PHP SDK Guide](http://parseplatform.github.io/docs/php/guide/) or dig through the ```ParseUser``` class. Best of luck!
