### ISSUE TITLE
1.15 to 1.17 batch upgrade

### ISSUE THREAD

**Issue by foloed** [ParsePlatform/parse-php-sdk#186]
Our php app recently upgraded from 1.1.5 to 1.1.7 and we ran into an issue that prevents all of our batch saves from saving. Does anyone know of any existing issues that could be causing this?

<h1>500 Internal Server Error</h1><h3>Method 'POST' to 'classes/sample' not supported in batch operations. (107)</h3>

Any help is appreciated!

Matt

**Comment by gfosco** [comment]
Yes, there was a change made in 1.1.7 that appears to have broken it, and it was patched 4 days ago.

I just tagged 1.1.8 so you should be able to update now.  Thanks.
