### ISSUE TITLE
couldn't resolve parse.api.com , Error code - 6 with parse-php-sdk

### ISSUE THREAD

**Issue by soniurvashi11** [ParsePlatform/parse-php-sdk#188]
I am unable to even login in my website which is parse-php-sdk based .I got couldn't resolve parse.api.com error with Error code - 6 ,Do i have to change something in my code ?I really want some permanent solution with this ,This problem occurs only with my remote host and not my localhost . Whats the exact issue and how can i get rid of this issue permanently .Please help .It automatically resolves afterwards but I need a permanent solution for this .

**Comment by phelipealves** [comment]
which is the version used?

**Comment by soniurvashi11** [comment]
php version 5.4.27

**Comment by gfosco** [comment]
I'm sorry, but I don't see anything we can do to resolve this.  DNS resolution happens outside the SDK, and you would need to troubleshoot by other means.  I'd start here:  https://www.google.com/search?q=dns+intermittently+fails
