### ISSUE TITLE
Stuck on error : Class 'Parse\ParseClient' not found 

### ISSUE THREAD

**Issue by techip** [ParsePlatform/parse-php-sdk#189]
Hi, everybody!
I just started my 1st trials with FB API 5 - last vs, for PHP and after setting up everything, I just can't get this error out of my way. It's all pretty new to me and and I'm just following the manuals, so I'm really in a hard time. Follows a small report I worked on to better demonstrate the issue and what I find strange about it all. 
I really hope anybody lend me a helping hand, because i'm totally lost. 
Thanks in advance!

![1](https://cloud.githubusercontent.com/assets/10259383/11224520/816932d0-8d5c-11e5-9171-96926718ed03.png)
![2](https://cloud.githubusercontent.com/assets/10259383/11224518/81383b80-8d5c-11e5-9c4f-eef673784233.png)
![3](https://cloud.githubusercontent.com/assets/10259383/11224516/81359826-8d5c-11e5-8b78-c272a5ba8838.png)
![4](https://cloud.githubusercontent.com/assets/10259383/11224517/8138017e-8d5c-11e5-94c8-24ad751877c2.png)
![5](https://cloud.githubusercontent.com/assets/10259383/11224519/81398238-8d5c-11e5-9e07-7d6020ef15a8.png)

**Comment by smartfin** [comment]
Not sure, but as i can see in your ./vendor/ dir there is no 'parse' directory. Make sure, you added 
 "parse/php-sdk" : "1.1.*" to 'require' section of your composer.json file.

If you already added that, maybe you forgot run 'composer update' ?
