### ISSUE TITLE
How to get push delivery status

### ISSUE THREAD

**Issue by hbabhishek** [ParsePlatform/parse-php-sdk#190]
We are sending push notifications to Android users through Parse web API. Some users are reporting that they are not getting push notifications.

Please guide us on how to get delivery status of push notifications sent through web API.

I am using following PHP code to initiate parse push for android device user -

```
function androidParseNotification($device_id = '', $message = 'hi', $extra = array()) {
       /*echo $device_id;
       echo $message;exit;*/
      $url = 'https://api.parse.com/1/push';
      $result = '';
      try {
           if (empty($device_id)) {
           throw new Exception("Device token not found..!");
           }
    if(is_array($device_id))
    $device_id = implode(',', $device_id);
    $device_tokenArr = explode(',', $device_id);

    $APPLICATION_ID = $this->CI->config->item('PARSE_APPLICATION_ID');
    $REST_API_KEY = $this->CI->config->item('PARSE_REST_API_KEY');

    if (empty($REST_API_KEY) || empty($APPLICATION_ID)) {
        throw new Exception("Push notification Authorization key not found..!");
    }
    $payLoadArray = $extra;
    $payLoadArray['alert1'] = $message;
    $push_payload = json_encode(array(
                                   "where" => array(
                                "objectId" => array('$in' => $device_tokenArr),
                        ),
            "data" => $payLoadArray
    ));
    //pr($push_payload);
    if (!function_exists('curl_version')) {
        throw new Exception("CURL is not installed in this server..!");
    }

    // Open connection
    $rest = curl_init();
    if (!$rest) {
        throw new Exception("CURL intialization fails..!");
    }
    // Set the url, number of POST vars, POST data
    curl_setopt($rest,CURLOPT_URL,$url);
    curl_setopt($rest,CURLOPT_PORT,443);
    curl_setopt($rest,CURLOPT_POST,1);
    curl_setopt($rest,CURLOPT_POSTFIELDS,$push_payload);
    curl_setopt($rest, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($rest,CURLOPT_HTTPHEADER,
            array("X-Parse-Application-Id: " . $APPLICATION_ID,
                    "X-Parse-REST-API-Key: " . $REST_API_KEY,
                    "Content-Type: application/json"));

    // Execute post
    $response = curl_exec($rest);
    //pr($rest);
    //pr($response);
    // Close connection
    curl_close($rest);
    //exit;
    if (!$response) {
        throw new Exception("CURL execution fails..!");
    }

    $success = 1;
    $message = "Push notification send successfully..!";
} catch (Exception $e) {
    $success = 0;
    $message = $e->getMessage();
}

return $success;
```

}

**Comment by gfosco** [comment]
The status isn't available through the API.  I'd check the push console on parse.com and see if you can find any further information there.  Push notifications are notoriously difficult to troubleshoot and all platform providers don't guarantee delivery (only best-effort.)

**Comment by Stafox** [comment]
For now it possible: parse platform returns pushStatusId in **X-Parse-Push-Status-Id** header.

**Comment by montymxb** [comment]
@Stafox I took a look and you certainly can get the ```X-Parse-Push-Status-Id``` header back for ```_PushStatus```. I'm not looking into setting this up myself, but I'm going to reopen this so we get focus on this. If I have a moment or two in the near future (and noone else has chipped in) I'll take a look at writing something up for this.

**Comment by Stafox** [comment]
@montymxb thanks. I'll take a look

**Comment by Stafox** [comment]
For me as temporary solution I modified `ParseClient::_request` method and his call inside `ParsePush::send()` like this.
https://gist.github.com/Stafox/17cb099cc700972d38f4ef3379f72ac6
it allows to get array of headers under `_headers` key.

**Comment by montymxb** [comment]
@Stafox nifty little hack you have there. Just a heads up the sdk has recently changed regarding ```ParseClient::_request```, be sure to incorporate those new changes on your end (and in your gist too if you can); it's mostly patches for working with ```ParseFile```. 

If anyone is willing to put together a PR allowing something like ```ParseClient::_request``` to return headers (like the push status id) and (potentially) modifying ```ParsePush::send``` to return the actual ```_PushStatus``` object I would be willing to take a look at that 👍 . That would allow us to get some fairly direct feedback regarding pushes after they're sent. If I'm correct I don't think any of the other SDKs even have anything like that in place... this could be the first.

**Comment by Stafox** [comment]
@montymxb ok. I will fix it in according with latest changes. Also I will make chages to follow redirects and handle multiple headers. When it will be ready I will create a PR.

**Comment by Stafox** [comment]
Here is it: #279

**Comment by montymxb** [comment]
Changes from #279 are in. Thanks again @Stafox ! The only other thing I can think of is that we might want a ```ParseObject``` subclass for the ```_PushStatus``` class sometime in the future, just to make things easier. But for now this is a step in the right direction 👍 .
