### ISSUE TITLE
Multiple device registered in Parse Push account

### ISSUE THREAD

**Issue by MohasinHB** [ParsePlatform/parse-php-sdk#191]
Hello Support Team,

In our Android application, total we have 10K user are registered but Parse console display 12K Object ID, means few users multiple object Id registered in account.

Now when I send push from console - push compaign then few users are getting more then one push notification.

Will you please guide us to resolve this multiple push delivery issue via compaign push.

Looking forward for your response.

Thanks,
Mohasin.

**Comment by gfosco** [comment]
This is not a PHP SDK related issue and could be reported as a bug through https://parse.com/help

However, I suspect this relates to Android issues with old SDK versions and not using GCM.  Users receiving multiple messages should be able to fix this by deleting the app entirely and reinstalling.

Also, User and Installation counts don't typically match.
