### ISSUE TITLE
Very slow data fetching from parse

### ISSUE THREAD

**Issue by Jonnyhunka** [ParsePlatform/parse-php-sdk#192]
We are using php sdk for fetching data to our web app (developed in php). But data fetching is very very slow and hence the loading of overall webpage becomes very slow. We have stored very few data in our parse database but response is very slow.

As soon as we disconnect the database from the application, the overall application loads quickly but when connection between application and database is estabilished the app takes huge time to load fully.

Kindly provide solution to this problem on urgent basis as our app is live and the issue must be resolved on urgent basis.

**Comment by Jonnyhunka** [comment]
Kindly provide solution ASAP.

**Comment by gfosco** [comment]
You may have a problem with your server environment, as typically the connection and usage of the database is quite fast.  Put together some CURL commands to test this, and test other hosts as well.  This does not appear to be an SDK issue as far as I can tell.
