### ISSUE TITLE
GeoPoint fails when lat,lng is not a float. 

### ISSUE THREAD

**Issue by awgeorge** [ParsePlatform/parse-php-sdk#193]
Just stumbled into a problem that a few may have faced. Upon submitting lat, lng values trough a web form, the resulting data is in string format.

There is no exception thrown from the PHP wrapper, but upon contacting the REST Client, the server spits out the data for not being a float. (Its also quite an unhelpful error)

Should we stop the wrapper making the API request, or should we cast to a float on behalf of the user? If the latter, we could check `is_numeric` before we cast.

**Comment by mauriciord** [comment]
ParseGeoPoint
