### ISSUE TITLE
updating and existing record using this SDk

### ISSUE THREAD

**Issue by mzeeshan88** [ParsePlatform/parse-php-sdk#196]
hi dear

can you please help me and give me the example to update an existing record in parse.com using php parse sdk ??
i have tried other solutions like below but no success 

$query = new ParseQuery("Event");
$query->equalTo("event_identifier", "31621613216061321630");
$question = $query->find();

// Manipulate the object and save it
$question->set("event_name", "this");
$question->save();

can you help on this?? im really need it and urgent :(

thanks in advanced 

kind regards

**Comment by luisbatista** [comment]
You don't write details about the issue you have to update a record!

But, I think your problem is that you get an array of records:
```
$question = $query->find(); // <== here get an array
```
And can't change the value and update.

Try this:
```
$questions = $query->find();
$question = $questions[0]; // is better to validate if you get more records and create the code to manage this situation

// Manipulate the object and save it
$question->set("event_name", "this");
$question->save();
```

**Comment by soniurvashi11** [comment]
The only problem is u r getting array of records with $question =$query->find()
Use $query->first(),it will return only one record and hence u can update successfully

**Comment by mzeeshan88** [comment]
thank you for your reply 

i have another problem if i save one record it do work and update the data on parse.com but when i update more than one record it does not update :( 

$query = new ParseQuery("Event");
$query->equalTo("event_identifier", $event_identifier);
$question = $query->first();

// Manipulate the object and save it
$question->set("event_name", $event_name);
$question->set("start_date", $start_date);
$question->set("event_identifier", $event_identifier);
$question->set("event_desc", $event_desc);
$question->set("reg_limit", (int)$reg_limit);
$question->set("event_location", $event_location);
$question->set("event_address", $event_address);
$question->set("event_city", $event_city);
$question->set("event_state", $event_state);
$question->set("event_postal", $event_postal);
$question->set("location_list", $location_list);

$question->save();

 this code does not update the fields help pleaseeeeee

**Comment by soniurvashi11** [comment]
See ,if u want to update one record then use $question = $query->first();
But if u want to update multiple objects u have to go with $questions = $query->find();
Let's take an example,suppose u want update all events with event name ="event1". Following code will work---->

$query = new ParseQuery("Event");
$query->equalTo("event_name", "event1");
$question = $query->find();
for($i=0;$i<count($question);$i++)
{
$question[$i]->set("event_city", $event_city);
$question[$i]->set("event_state", $event_state)
$question[$i]->save();
}

**Comment by soniurvashi11** [comment]
Please ignore above comment.
See ,if u want to update one record then use $question = $query->first();
But if u want to update multiple objects u have to go with $questions = $query->find();
Let's take an example,suppose u want update all events with event name ="event1". Following code will work---->

$query = new ParseQuery("Event");
$query->equalTo("event_name", "event1");
$question = $query->find();
for($i=0;$i;$i++){
$question[$i]->set("event_city", $event_city);
$question[$i]->set("event_state", $event_state)
$question[$i]->save();
}

**Comment by mzeeshan88** [comment]
yes i have fixed the problem thank you very much .. now i have another question i want to delete an record :) what i have to for that?? any idea>>

**Comment by luisbatista** [comment]
Easy :)

```
$question->destroy();  // delete a record
```
or
```
$question->delete("fieldname");  // empty a field on a record
```

**Comment by soniurvashi11** [comment]
You use destroy,first find using Id or any other parameter,nd use destroy same as u used save(),first() for single record and find() with loop for multiple

**Comment by luisbatista** [comment]
https://parse.com/docs/php/guide   to know more about Parse.com PHP

**Comment by mzeeshan88** [comment]
thank you very much soniurvashi11 and luisbatista  really appritiate your help and support :)

**Comment by soniurvashi11** [comment]
Anytime :)

**Comment by devestatic** [comment]
Hello guys, 

Can you please help me for update object column in parse?
please check screenshot - https://prnt.sc/jpcl3r
My code is 
$nutritionresult->set("nutritionalGoals", $updated_goalDict);
$nutritionresult->set("macrosRatio", $updated_protRatio);
$nutritionresult->save();
but its not working. given 500 internal server error

Regards,
Dev
