### ISSUE TITLE
How to import CSV data via PHP SDK

### ISSUE THREAD

**Issue by mahavirtechnosip** [ParsePlatform/parse-php-sdk#200]
Hello,

I want to import CSV data via PHP SDK. Please suggest the possible solutions. is there any function exists where i pass file name and parse class name and the csv data will be uploaded automatically via parse php sdk.

Thanks :)

**Comment by vaibbhav** [comment]
It helps you !
<?php 
    //This example is a sample video upload stored in parse
    
    $parse = new parseObject('Videos');
    $parse->title = $data['upload_data']['title'];
    $parse->description = $data['upload_data']['description'];
    $parse->tags = $data['upload_data']['tags'];
    
    //create new geo
    $geo = new parseGeoPoint($data['upload_data']['lat'],$data['upload_data']['lng']);
    $parse->location = $geo->location;
    
    //use pointer to other class
    $parse->userid = array("__type" => "Pointer", "className" => "_User", "objectId" => $data['upload_data']['userid']);
    
    //create acl
    $parse->ACL = array("*" => array("write" => true, "read" => true));
    $r = $parse->save();
    ?>

**Comment by mahavirtechnosip** [comment]
@vaibbhav Thanks for writing back, I want to import data from CSV file to parse via PHP SDK, not looking for uploading files.

**Comment by gfosco** [comment]
You'll have to read through and loop the CSV data, creating parse objects and saving them along the way...
