### ISSUE TITLE
How to send notify multiple device WHERE? 

### ISSUE THREAD

**Issue by nguyenlehuutai** [ParsePlatform/parse-php-sdk#202]
Hello, 
- I want to send notify multiple device.
- This is my sample.

```
$query = ParseInstallation::query();
$query->equalTo('deviceToken', 'xxxxxxx');
$query->equalTo('deviceToken', 'abcd');
        
$data = [
  'data'  => ['alert' => 'Hello, this is a test'],
  'where' => $query,
];
ParsePush::send(
  $data
);
```

- But it is send notify for device have token is 'abcd'
- How to send notify multiple device WHERE ?
Thanks

**Comment by gfosco** [comment]
You can't use equalTo twice on the same key.  You can use containedIn and provide an array.

```
$query->containedIn('deviceToken', ['xxxx', 'abcd'];
```

**Comment by nguyenlehuutai** [comment]
Thank you. I solved it.
