### ISSUE TITLE
Add simple array extraction option(s)

### ISSUE THREAD

**Issue by tucson-tom** [ParsePlatform/parse-php-sdk#203]
Applications may not necessarily know the field names in a Parse query.  The only current method to getting data out of Parse in these circumstances is to use the semi-private ParseObject::_encode() function and then decode the serialized JSON data afterwards (kind of wasteful on system resources AND is calling a method you probably aren't expecting anyone outside of the SDK to call) OR modify the SDK to make some of the information public instead of protected (also not desirable).

Please add a method to return either 'serverData' or 'estimatedData' (or both) as a standard PHP array.

**Comment by gfosco** [comment]
I would accept a PR which provides a getter on the estimatedData.

**Comment by montymxb** [comment]
You can get estimatedData from the existing method ```ParseObject::getAllKeys()```, which returns the estimatedData as a php array. As far as I know there is no method to pull out serverData directly, but I'm assuming this would address the field names issue.
