### ISSUE TITLE
invalid session token on any API calls.

### ISSUE THREAD

**Issue by adadgio** [ParsePlatform/parse-php-sdk#205]
Parse PHP SDK now throws an "invalid session token" on any API call (even when not trying to merge a user).

**Comment by gfosco** [comment]
It sounds like you're trying to use an expired/invalid token... You'll need to provide more information if you think there is an issue with the SDK and you can reproduce this behavior.  Thanks.

**Comment by adadgio** [comment]
It happened because i create a user using ParseUser and then tried an API request, which worked before.

No code was changed in the meantime. Could it be the SDK confuses user sessions and API/keys/sessions, or whatever ?

When i create a Parse user using a new ParseObject and settings fields on blank and using masterKey, it however works.

**Comment by gfosco** [comment]
Can you show some code?  It's still very unclear where the issue is happening.
