### ISSUE TITLE
too slow queries 

### ISSUE THREAD

**Issue by ChumburidzeGio** [ParsePlatform/parse-php-sdk#206]
Hello, I made app on laravel and its too slow (about 1.3s) i wondered that its by framework and I have created droplet on DO (Ubuntu 15.04 + HHVM) 
created index.php with code 
```<?php
require 'vendor/autoload.php';
use Parse\ParseQuery;
use Parse\ParseClient;

ParseClient::initialize( 'WkcImBxxeenSfqlWSnATkjNYigxH199GPpEbRmYg', 's1DwdeR5p594JIpgdGWGg4bXW506LmbMuaTHBMLY', '8zd4c0ssfXCfqYRaiyCIXxIxLxXhQhGtI4z5OOJC' );

$query = new ParseQuery("Post");

return $query->count();```


and i got the same - 811 ms needed for just this query ...

Its something with Parse.com now or its always so slow? 

HELP PLEASE

**Comment by gfosco** [comment]
It is not recommended to run count queries on Parse.  It is instead recommended to keep a counter on an object incremented and decremented using the cloud code triggers when things change.  Count queries are not-performant or scalable in many NoSQL storage systems.

**Comment by ChumburidzeGio** [comment]
$query = new ParseQuery("Post");

$object = $query->get("izDXkWUfmh");

var_dump($object);


this request takes 680ms and its not count query

**Comment by ChumburidzeGio** [comment]
810 ms for signing up user ...
is there any solution for it?

**Comment by gfosco** [comment]
What if you make the same request with curl to the REST API?... 

```
curl -X GET \
-H "X-Parse-Application-Id: yourAppId" \
-H "X-Parse-REST-API-Key: yourRestKey" \
https://api.parse.com/1/classes/Post/izDXkWUfmh
```

**Comment by ChumburidzeGio** [comment]
600 - 1200 ms :(

**Comment by gfosco** [comment]
Where are you located?  Parse is in the east coast amazon data center.

**Comment by ChumburidzeGio** [comment]
I'm in Georgia (Republic) and I use DO located in Frankfurt

**Comment by ChumburidzeGio** [comment]
Can locate Parse in Europe too?

**Comment by gfosco** [comment]
Let me get back to you on this next week.

**Comment by ChumburidzeGio** [comment]
Think i will move to AWS but if possible to make Parse more faster i'll be very happy 
Thanks
