### ISSUE TITLE
Bad Request when querying using notContainedIn with more than 73 objects in array pointers

### ISSUE THREAD

**Issue by christopherdev** [ParsePlatform/parse-php-sdk#209]
hi,

I have 100+ objects in table A to compare to table B which is created by users,
when I query 73 objects it does work and checking on content type it is application/json
but when I make it > 73 it gives the error and the content type now is text/html.

also when I use skip still the same result, so I think it is not an issue with the existing objects

any idea what is causing the issue?

thanks

**Comment by FredvanRijswijk** [comment]
What query are you have? timeout?

**Comment by christopherdev** [comment]
hi,

this is how the query looks like
$query = new ParseQuery("class");
$query->notContainedIn('column', array of pointers);
$query->limit(73); returns data > 73 returns bad request

and no it doesn't timeout

**Comment by FredvanRijswijk** [comment]
https://github.com/ParsePlatform/parse-php-sdk/issues/132 is same ?

**Comment by christopherdev** [comment]
yeah

**Comment by gfosco** [comment]
Can you reproduce this using just curl calls and the rest API?

**Comment by christopherdev** [comment]
hi, 
my issue is the URL limitation since it is a GET request
