### ISSUE TITLE
Issue with filtering list of items

### ISSUE THREAD

**Issue by uaoleg** [ParsePlatform/parse-php-sdk#210]
In my collection I have a column named client. When I get the whole list of items (without any filters), it returns 26 items that have value for client column equal to "foo". But as soon as I apply any filter (e.g. client = "foo", or client != "bar") I get only 2 items that have value for client column equal to "foo".

Filtering works fine for all the other client values (e.g. "bar", "baz", etc).

The issue is reproduced both for API and Parse Core (website).

**Comment by gfosco** [comment]
I would suggest opening a bug report through parse.com/help (scroll down and find the bug icon).. 

Include curl REST API calls to reproduce this (including your app id and rest api key headers) and it will be investigated.  Thanks.
