### ISSUE TITLE
Send curl Push

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/parse-php-sdk#215]
I'm trying to send curl push but I get this error :  `{"code":115,"error":"Missing the push channels."}`
I want to send the push for all channels and devices.
my curl code : 
```
curl -X POST -H "X-Parse-Application-Id: **" -H "X-Parse-REST-API-Key: **" -H "Content-Type: application/json" -d '{"appVersion":"1.2.2", "data":{"alert":"nn234","badge":"Increment","sound":"**","tweet_id":"FQrqomGzUv"}}' https://api.parse.com/1/push
```

**Comment by gfosco** [comment]
Looks like this question may help you:  http://stackoverflow.com/a/23002516/353988
