### ISSUE TITLE
Request encoding

### ISSUE THREAD

**Issue by dpgover** [ParsePlatform/parse-php-sdk#216]
Hi all,

Is there a way to send emojis using the API?

If I make a json like this ```{"alert": "Message text \ue043"}```
The push arrives as is. The phone does not change the unicode char for the emoji.

If I send the same json using parse web, the emoji arrives as intended...

This is for iOS.

Any ideas?

Thanks

**Comment by dpgover** [comment]
I found out that the request should be made using this header: ```application/json;charset=utf-8```

From this docs: https://www.parse.com/docs/cloudcode/guide#networking-post

**Comment by montymxb** [comment]
Sounds like you were able to take care of the issue here. If so you can probably close this.
