### ISSUE TITLE
Parse retired, in PHP SDK can i change serverURL ? from PARSE Server

### ISSUE THREAD

**Issue by mauriciord** [ParsePlatform/parse-php-sdk#222]
Hello, Parse made a announcement that will retire on 2017, you know that they provided the Parse Server.
At [Docs](https://parse.com/docs/server/guide), they say to change server URL at Javascript for example:

```javascript
Parse.initialize("YOUR_APP_ID", "YOUR_APP_CLIENT_KEY");
Parse.serverURL = 'http://localhost:1337/parse'
```

Is there a way to make that in PHP SDK ?
Thanks.

**Comment by gateway** [comment]
Any Updates to this? I need to work in migration of our app and we have some admin backend stuff that talks to parse.

**Comment by globyworks** [comment]
I second that (or third that :P) any updates to change the server url ?

**Comment by globyworks** [comment]
Just realised there is a PR for that. Havent tested it yet though. Will do..

**Comment by fraxool** [comment]
If it can help someone, I wrote a complete answer which works for me, on Stackoverflow : 

http://stackoverflow.com/a/35132450/4569921

**Comment by gfosco** [comment]
Updated in 1.2.0:

```
ParseClient::setServerURL('https://myapp.herokuapp.com/parse');
```
