### ISSUE TITLE
Parse Push - PHP SDK

### ISSUE THREAD

**Issue by globyworks** [ParsePlatform/parse-php-sdk#223]
Hi all,

I tried to test the new "opened sourced" push functionality of the Parse Server, using a PHP app i had build when parse was hosted.

The new setup (on heroku) tried to trigger a file "ParsePush.php" which is not available as far as i can see (ERROR: 3.4251	1228744	Parse\ParseClient::_request( )	../ParsePush.php:75).

Maybe this will be available soon on a PHP SDK update?
Am i missing something here ?

**Comment by gfosco** [comment]
In 1.2.0 you should be able to send push:

```
ParsePush::send($data, true);
```
