### ISSUE TITLE
[Parse Server] clientKey is optional if using Parse Server

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/parse-php-sdk#225]
A client key (or REST API Key) does not need to be configured in order to deploy a Parse Server. The Parse PHP SDK does not currently support connecting to a clientKey-less Parse Server.

To resolve this, the ParseClient initialization method should be updated so that the $rest_key parameter is made optional.

We should also remove any exceptions that may be thrown if a client key is not provided.

**Comment by jakelisby** [comment]
@hramos would this result in an "unauthorized" error when my Parse Server is deployed on AWS (not using a client key)?

**Comment by montymxb** [comment]
@jakelisby If no client keys are configured for the parse server you are connecting to you should be able to pass ```null``` or a string, it should be ignored upstream. The relevant section regarding client keys in parse server is [here](https://github.com/ParsePlatform/parse-server#user-content-client-key-options) also for info on that.

There is a section in ```ParseClient::_getRequestHeaders``` that will still send the ```X-Parse-REST-API-Key``` header when the request does not indicate to use the master key. This header should be ignored, but ideally it should not be sent at all if the rest api key is ```null```. I can put together a PR when I have a moment that makes the appropriate changes.
