### ISSUE TITLE
issue with objectId that starts with number (e.g 54abcDEF)

### ISSUE THREAD

**Issue by christopherdev** [ParsePlatform/parse-php-sdk#227]
hi,

I am having issues with data with objectId that starts with numbers, not really sure if it is the real cause but I am only experiencing with those objectId's

when queried solo like this
$query = new ParseQuery("Test");
$query->containedIn('objectId', ['54abcDEF']);
it does returns but when adding 
$query = new ParseQuery("Test");
$query->containedIn('objectId', ['54abcDEF', 'anotherID']);
only the anotherID is return, it is also the same with pointers
and also happening in IOS SDK

**Comment by montymxb** [comment]
I've don't believe there's an issue regarding object ids which start with a digit. If you're still having an issue it's probably something else, but I'm going to close this for now.
