### ISSUE TITLE
Fatal Error when calling ParseUser::getCurrentUser before ParseClient::initialize

### ISSUE THREAD

**Issue by kororo** [ParsePlatform/parse-php-sdk#243]
Hi There,

I understand this is human error that I called ParseUser::getCurrentUser before the ParseClient::initialize
FatalErrorException in ParseUser.php line 335: Call to a member function get() on a non-object

It should behave similarly as ParseUser::become
ParseClient.php line 402: You must call Parse::initialize() before making any requests.

I will assign this to myself (if possible) and will do some update.

Thanks
Rob

**Comment by gfosco** [comment]
Sure if you want to change it, I'd accept the PR.  Otherwise I'm okay with the current behavior.
