### ISSUE TITLE
Anonymous UUID isn't formatted correctly.

### ISSUE THREAD

**Issue by ay8s** [ParsePlatform/parse-php-sdk#245]
Using PHP 7 it looks like the UUID for anonymous users isn't formatted correctly. The output doesn't include any of the generated UUID from above this line... https://github.com/ParsePlatform/parse-php-sdk/blob/1f668b97b229829f2ed05e23fd38685cc9e2c62b/src/Parse/ParseUser.php#L201

Changing it to the following works...
```
        $uuid_parts = str_split(md5(mt_rand()), 4);
        $data = ['authData' => [
            'anonymous' => [
                'id' => $uuid_parts[0].$uuid_parts[1].'-'.$uuid_parts[2].'-'.$uuid_parts[3].'-'.$uuid_parts[4].'-'.$uuid_parts[5].$uuid_parts[6].$uuid_parts[7],
            ],
        ]];
```

**Comment by gfosco** [comment]
Can you submit a PR?
