### ISSUE TITLE
New update error for ParseClient::setServerURL

### ISSUE THREAD

**Issue by gate3** [ParsePlatform/parse-php-sdk#247]
I can see there is a new update to ParseClient. It used to be 
`setServerURL($serverURL)` 
but it's now 
`setServerURL($serverURL, $mountPath)`
It hasn't been documented yet and its been causing me errors all day.

**Comment by montymxb** [comment]
Use of `setServerURL` splits the existing call into two parts now. The server url, and the mount path. 

For example a prior call as follows:
```php
ParseClient::setServerURL('https://my-parse-server.com/parse');
```
 Would now look like this:
```php
ParseClient::setServerURL('https://my-parse-server.com','parse');
```
 Additionally this has been updated in the README.md. 

If you're wondering, this was put in place to fix an issue regarding batch operations. They were utilizing a hardcoded `/1` as your current mount path, rather than your actual mount path.

**Comment by gate3** [comment]
Oh ok. I am using a Laravel package for my connection to parse and it
apparently does not know about this yet or it does not work for me. It is
not getting split. I will var_dump what is getting sent to ParseClient to
ensure. I manually corrected this for now by using thesame url as my server
url.

**Comment by montymxb** [comment]
I see this is still open, were you able to resolve your issue regarding Laravel?

**Comment by gate3** [comment]
So sorry, I should have closed it. Yes I was able to thank you

**Comment by shalomabitan** [comment]
Hi, 

@gate3 Can you detail how you were able to correct this.

Thanks

**Comment by gate3** [comment]
OK,  I just edited the file published by the parse library in the config directory, by adding the required key called mount path into the array it passes on to the php sdk. I split the serverURL in two,  putting only 'parse/' in mount path and the rest in the serverUrl.  I then go on and edit the sdk itself, by manually using the mount path from the array and the serverUrl like so:

ParseClient::setServerURL(array['serverUrl'],array['mount_path']);

Thats a rough idea of how I did it. I will post some real code from my PC,  i am on my phone now.

**Comment by gate3** [comment]
Hi ParsePlatform/parse-,

I'd like to add you to my professional network on LinkedIn.

- Olarewaju

Confirm that you know Olarewaju: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Vyj2o7JO&invitationId=6179213000818376704&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eissolkey%7Eyd








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-issolkey-yd&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFdo68gQkvIEgAAAVcD5qc4cEcmaRWwkul1jV2eYE6igsQBvwcscBeCAKToysy1ZC2m6oVasiCoY3TA_vSVvdf2nT1fHVvtgPjqHbMgboy1M-fqbbkHmt8xN9NbP-sNGvHzac12RF9RF1IQx76vNVt0RQpPhewTGut4qked50yDX-w9wSVr0zqFrRPj6ZS5xXAb&eid=0-issolkey-yd


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-issolkey-yd&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by gate3** [comment]
Olarewaju Doyin would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Vyj2o7JO&invitationId=6179213000818376704&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Edo9owg%7Eit2vzlk7%7Ef1

View Olarewaju Doyin&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Vyj2o7JO&invitationId=6179213000818376704&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Edo9owg%7Eit2vzlk7%7Ef1





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-do9owg-it2vzlk7-f1&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-do9owg-it2vzlk7-f1&loid=AQH9IjkxdbV_8gAAAVcpRLWrQc2NETYlD-a4X9tpvhLdKd1oQDcJAwEgyf_qhlaRtyYAmZqpM36NMm6wdUCba3Xj419ZxOLKYtnxkX-JFIBbQilpknbpAx6G9DJ8FNnNPXEEHAm6pr5mfG2Tel1Xl4u1diq1k6gFEHHXcOgZaHF6WSeE-emPJx64gB8Bx8mscCmG

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-do9owg-it2vzlk7-f1&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by gate3** [comment]
Hi ,

Olarewaju Doyin would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Vyj2o7JO&invitationId=6179213000818376704&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Edo9owg%7Eitcvdwsz%7Ej7

View Olarewaju Doyin&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Vyj2o7JO&invitationId=6179213000818376704&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Edo9owg%7Eitcvdwsz%7Ej7





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-do9owg-itcvdwsz-j7&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-do9owg-itcvdwsz-j7&loid=AQHMC8ZW38RvVAAAAVdNSAgtsACDjdK7crtYDAL2kXJ_6OTwyEarwRl6H8Jtj7UJH2ZlH3KfjU3dqa2C0dPI96rui5eIK0wM7q6MUHuScAvknBI0XkHO45Fp9qQkD4y8HMDes3HA7hxG-Qbh-39F7xwHQiqSUqbhjBsPbh0m6hcd8KCXI4SW-NAGwy1qOQTBK3i5

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-do9owg-itcvdwsz-j7&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
