### ISSUE TITLE
Notice: Undefined offset: in 

### ISSUE THREAD

**Issue by token45** [ParsePlatform/parse-php-sdk#251]
Hi. I have 260 registered users. When i want fetch all registered users i get Notice: Undefined offset: 100 in error. I can't get all users. It just fetching first 99 records.

**Comment by token45** [comment]
I think find() method has a problem. I solved this using $query1->limit(10000). Now i can fetch all users.

**Comment by gfosco** [comment]
Queries have a default limit of 100, so that's what you're seeing.  Setting a higher limit is the correct solution if you want more.
