### ISSUE TITLE
user login with javascript sdk but not getting which user login with PHP SDK

### ISSUE THREAD

**Issue by naresh-git** [ParsePlatform/parse-php-sdk#254]
I am facing such a wired issue. i used JavaScript SDK to login in and successfully login. On the next page i am trying to get current user login using PHP SDK.
But strange no result coming, return NULL

using below code to do this ..

**JavaScript:**
```

Parse.User.logIn("myname", "mypass", {
  success: function(user) {
    // Do stuff after successful login.
  },
  error: function(user, error) {
    // The login failed. Check error to see why.
  }
});
```

**PHP:**

`$currentUser = ParseUser::getCurrentUser();`

Null Result here.

**Comment by naresh-git** [comment]
usin

**Comment by montymxb** [comment]
I don't believe logging in on one SDK carries over to another. You _could_ try and carry over a logged in user's data from one SDK to another manually, but I would recommend you try and stick with one SDK in it's entirety if possible.
