### ISSUE TITLE
Master key does not allow to read/write to classes with roles set

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-php-sdk#258]
We have set up various roles on our classes and removed public access, however the php code does not allow us to write to these classes.  

Looking at the code to initialize parse the master key is listed see 

```
require DRUPAL_ROOT . '/sites/all/libraries/parse-php-sdk/autoload.php';

use Parse\ParseObject;
use Parse\ParseQuery;
use Parse\ParseACL;
use Parse\ParsePush;
use Parse\ParseUser;
use Parse\ParseInstallation;
use Parse\ParseException;
use Parse\ParseFile;
use Parse\ParseClient;
use Parse\ParseGeoPoint;

$master_key = variable_get('parse_api_master', NULL);
$app_id = variable_get('parse_api_appid', NULL);
$rest_key = variable_get('parse_api_restkey', NULL);
$server = variable_get('parse_api_url', NULL);
$path = variable_get('parse_api_mount', NULL);

ParseClient::initialize($app_id, $rest_key, $master_key);  
ParseClient::setServerURL($server, $path);
```

Any reason why when using the master key we still cant read/write etc to our parse backend using php.. is their something special that needs to be done.  Note this is just an admin backend to pull and formate various data so we dont have really a user for the site.

Heroku logs

```
2016-09-14T00:08:04.446916+00:00 app[web.1]: error: Error generating response. ParseError {
2016-09-14T00:08:04.446929+00:00 app[web.1]:   code: 119,
2016-09-14T00:08:04.446930+00:00 app[web.1]:   message: 'Permission denied for action find on class UserTag.' } code=119, message=Permission denied for action find on class UserTag.
2016-09-14T00:08:04.449139+00:00 app[web.1]: [object Object]
```

**Comment by gfosco** [comment]
It's not enough to initialize it with the master key, you have to pass $useMasterKey=true to every save/query where you wish to use it.  Check the parameters for the call, i.e. https://github.com/ParsePlatform/parse-php-sdk/blob/master/src/Parse/ParseObject.php#L949

**Comment by gateway** [comment]
I would like to make a recommendation that you maybe post this on the front page read me since its not really clear.. thanks for the quick response!

**Comment by camdagr8** [comment]
+1 It's taken me DAYS to figure this out. Especially since I was able to CURL to my server w/o a problem.

**Comment by montymxb** [comment]
@gateway @camdagr8 the README has been updated with references to the usage of the master key in saving and querying. Hope this clears that up a bit.
