### ISSUE TITLE
User session invalid after user is idle

### ISSUE THREAD

**Issue by adambarghouthi** [ParsePlatform/parse-php-sdk#289]
Hi guys,

I'm trying to keep the user logged in and this is what I'm doing: 

```
if( session_id() == '' || !isset( $_SESSION ) ) {
    session_set_cookie_params( 2628000 /* 1 month */, '/', 'itsyuma.com', true );
    session_start();
}

ParseClient::initialize( '[app_key]', '', '[master_key]' );
ParseClient::setServerURL( '[server_url]', 'parse' );
ParseClient::setStorage( new ParseSessionStorage() );
```

the `session_set_cookie_params()` has helped me keep them logged in, but when they're idle it just logs them out for some reason. It doesn't seem to be persistent unless the user is constantly scouring the website. 

Is there something I'm missing? Thank you!

**Comment by montymxb** [comment]
Hey @adambarghouthi. Have your tried playing around with session [max lifetime](https://secure.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime)? By default I believe it's 24 mins, or 1440 seconds. 

** Note that [session.gc-probability](https://secure.php.net/manual/en/session.configuration.php#ini.session.gc_probability) and [session.gc_divisor](https://secure.php.net/manual/en/session.configuration.php#ini.session.gc-divisor) may affect this as well, depending how they are set.

Setting this can be done via a call to ```init_set```:
```php
// increase session max life to 1hr
ini_set('session.gc_maxlifetime', 3600);
```

However this may alter behavior in a way that's undesirable on your end. You may end up with a lot of extra sessions that take quite much longer to expire. 

If you don't want to mess with the session garbage collection you could try an 'auto refreshing' solution such as [this one on SO](https://stackoverflow.com/questions/5962671/prevent-session-expired-in-php-session-for-inactive-user#5964295). In this fashion users who are still on a page will remain active so long as it is open in their browser. Once they do leave gc cleanup will happen as is normally does.

Also you don't need to make this call:
```php
ParseClient::setStorage( new ParseSessionStorage() );
```
If you have setup a session in advance ```ParseClient``` will automatically detect this and use session storage when you call ```ParseClient::initialize```. This is a little snippet of where this happens, you can take a look at it yourself in the aforementioned method if you're interested:
```php
        if (!static::$storage) {
            if (session_status() === PHP_SESSION_ACTIVE) {
                self::setStorage(new ParseSessionStorage());
            } else {
                self::setStorage(new ParseMemoryStorage());
            }
        }
```

**Comment by adambarghouthi** [comment]
@montymxb Thank you so much! I'll try playing around max lifetime 👍

**Comment by montymxb** [comment]
No problem, if you manage to figure it out be sure to let us know what worked!

**Comment by adambarghouthi** [comment]
@montymxb will do :)

**Comment by montymxb** [comment]
@adambarghouthi any luck?

**Comment by adambarghouthi** [comment]
Hi @montymxb, sorry for the late reply. Ya the `ini_set('session.gc_maxlifetime', 3600);` helped to persist the session :) thanks a bunch!

**Comment by montymxb** [comment]
Alright I'll go ahead and close this then.
