### ISSUE TITLE
Unable to save bi-directionnal relation with dirty state

### ISSUE THREAD

**Issue by zeliard91** [ParsePlatform/parse-php-sdk#293]
Hi,

As showed with this test : https://github.com/zeliard91/parse-php-sdk/commit/1ff79037ec46c7f85b254771da17459ef7758cfe we are not able to complete the save process with a bi directional relations when an array of pointers is used and is in dirty state.

The output of this test is : 

```
Fatal error: Maximum function nesting level of '256' reached, aborting! in /srv/git/parse-php-sdk/src/Parse/ParseObject.php on line 1151

Call Stack:
    0.0001     232568   1. {main}() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/phpunit:0
    0.0047    1028424   2. PHPUnit_TextUI_Command::main() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/phpunit:52
    0.0047    1029048   3. PHPUnit_TextUI_Command->run() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/TextUI/Command.php:100
    0.0713    4674144   4. PHPUnit_TextUI_TestRunner->doRun() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/TextUI/Command.php:149
    0.0790    4896968   5. PHPUnit_Framework_TestSuite->run() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
    1.0236    9044632   6. PHPUnit_Framework_TestCase->run() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
    1.0237    9044632   7. PHPUnit_Framework_TestResult->run() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
    1.0249    9045592   8. PHPUnit_Framework_TestCase->runBare() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
    1.0255    9062448   9. PHPUnit_Framework_TestCase->runTest() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
    1.0256    9063256  10. ReflectionMethod->invokeArgs() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
    1.0256    9063504  11. Parse\Test\ParseRelationTest->testBiDirectionalRelations() /srv/git/parse-php-sdk/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
    1.0931    9074624  12. Parse\ParseObject->save() /srv/git/parse-php-sdk/tests/Parse/ParseRelationTest.php:213
    1.0931    9074672  13. Parse\ParseObject->isDirty() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:952
    1.0931    9074720  14. Parse\ParseObject->_isDirty() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:256
    1.0932    9074720  15. Parse\ParseObject->hasDirtyChildren() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:271
    1.0932    9075528  16. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:287
    1.0933    9076104  17. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1157
    1.0934    9092584  18. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1157
    1.0934    9092936  19. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1143
    1.0936    9093080  20. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1157
    1.0937    9093520  21. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1143
    1.0938    9094704  22. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1157
    1.0940    9094800  23. Parse\ParseObject::traverse() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1157
    1.0944    9096120  24. Parse\ParseObject->Parse\{closure}() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:1146
    1.0944    9096120  25. Parse\ParseObject->isDirty() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:282
    1.0944    9096168  26. Parse\ParseObject->_isDirty() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:256
    1.0945    9096168  27. Parse\ParseObject->hasDirtyChildren() /srv/git/parse-php-sdk/src/Parse/ParseObject.php:271
....
```

Thanks,

**Comment by montymxb** [comment]
Hey @zeliard91 I took a look at your test case and played around with it briefly. It would appear that your issue is in regard to whether or not `$child2` has been saved before it is added to the parent under ```children```. If you save the second child before like so:
```php
        $child2 = new ParseObject('BiChild');
        $child2->set('name', 'Child 2');
        $child2->set('parent', $parent);

        // save before adding this child
        $child2->save();

        $parent->setArray('children', [$child, $child2]);

        $parent->save();
```
you should find that your test case passes. It would appear the child objects internally are copied instead of referenced. However, this _should_ be fixed to throw a valid exception instead of a nesting crash. 

I can take a look at putting something in to achieve this when I have a moment. If you or another wants to tackle this I would be willing to accept a PR which catches unsaved objects being passed in as array elements at the proper juncture.

Other than that thanks for bringing this to our attention! Hopefully we can get this patched up soon.

**Comment by montymxb** [comment]
It looks like ```ParseObject::hasDirtyChildren``` is in fact causing this issue by calling ```$object->isDirty()```. This call will result in the a tight loop where the child, to be validated, must check the parent and the parent must in turn check the child. Modifying the call to ```$object->_isDirty(false)``` negates this endless child checking loop by indicating we should not consider children of this object when checking for dirtiness.
```php
$result = false;
self::traverse(
	true,
	$this->estimatedData,
	function ($object) use (&$result) {
		if ($object instanceof ParseObject) {
                        // modified isDirty to _isDirty and pass false
			if ($object->_isDirty(false)) {
				$result = true;
			}
		}
	}
);

return $result;
```
Even though we are not explicitly checking children for dirtiness now, we are still able to determine if an object is dirty via it's children (or children of children for that matter) as the ```traverse``` method will pass through all key/value pairs of each object; recursing into any ParseObjects it finds. Taking a look at this on my end (with your particular test case included) all tests pass. However I would like to get some feedback from your end that this does in fact fix your observed issue before I move forward with a PR.

**Comment by zeliard91** [comment]
Hi @montymxb , your solution resolves the issue that I have in my project.
I have a case where I make cascade persits of different objects whose relations can be circular.

The test pass too, so it looks good to me to be a PR, thank you very much !

**Comment by montymxb** [comment]
Glad to hear it @zeliard91 ! I'll keep this open until the patch is applied.

**Comment by montymxb** [comment]
Thanks again for bringing this up so we could take care of it 👍

**Comment by zeliard91** [comment]
Great, thank you for the PR @montymxb ! 
Could you tag it to make a release please ?

**Comment by montymxb** [comment]
@zeliard91 release [1.2.4](https://github.com/ParsePlatform/parse-php-sdk/releases/tag/1.2.4) is up for the bi-dir fix. Thanks for catching that!
