### ISSUE TITLE
how to make a Parse Relation?

### ISSUE THREAD

**Issue by cinder92** [ParsePlatform/parse-php-sdk#299]
i have a Class Tag and a Class News, News have a relation whit Tag, how can i make this relation with this sdk?

thanks

**Comment by montymxb** [comment]
@cinder92 take a moment to read the [docs](http://parseplatform.org/docs/php/guide/). The answer to your questions will almost always be there in regards to how to using this sdk. In particular the section regarding [relational data](http://parseplatform.org/docs/php/guide/#relational-data) might be of interest to you.

**Comment by cinder92** [comment]
@montymxb sorry i just found docs after i just published this issue, but thanks.
