### ISSUE TITLE
Facebook Sign up Login

### ISSUE THREAD

**Issue by manuvendev** [ParsePlatform/parse-php-sdk#35]
Good morning!

I am trying to sign up and login my users through facebook, I alreday included the auth method for users using Facebook PHP SDK, once the user logs in facebook returns a code but I don't know how to link that with a PFUser from Parse. As it has nothing to do with the authData field used in Android or iOS.

Has anyone tried this?

Thanks in advance.

**Comment by alexissusset** [comment]
+1 this feature would be great

**Comment by manuvendev** [comment]
I managed to do this using the REST API as Fosco said together with
Facebook PHP SDK, however it was a bit painful to parse all the dates and
so. I'll try to post some code asap.


*Manuel Ventero*
@manuvendev 667.366.095

2015-01-03 23:50 GMT+01:00 Alexis Susset <notifications@github.com>:

**Comment by marcusbrose** [comment]
+1

**Comment by gfosco** [comment]
Anyone willing to review/test #90 ?

**Comment by cristiana214** [comment]
+!

**Comment by sherizan** [comment]
+1

**Comment by cristiana214** [comment]
i made it work with Facebook  and Twitter using rest api

**Comment by lupena** [comment]
+1
