### ISSUE TITLE
Include certificate bundle and CURL fallback for ssl_verifypeer failures

### ISSUE THREAD

**Issue by sergiopello** [ParsePlatform/parse-php-sdk#4]
Hi,
When I try the sample in https://parse.com/apps/quickstart#parse_data/php I get the following error:
SSL certificate problem: unable to get local issuer certificate
at the moment of $testObject->save();
What configuration (I'm running Apache) should I use to solve this issue?

Any help would be grateful

Thanks in advance

**Comment by NandoSantana** [comment]
Hi Allinora, not yet left the fix, modified the _REQUEST function, now I can see this error on login,
Warning: file_get_contents(http://api.parse.com/1/login?email=XXXXXXXXXX&password=XXXXXXXXXX): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in /home/color813/public_html/src/Parse/ParseClient.php on line 220

**Comment by buidinhnguyen** [comment]
Hi @allinora
I tried to modify the ParseClient, but met this issue:

A PHP Error was encountered

Severity: Warning

Message: file_get_contents(http://api.parse.com/1/classes/TestObject): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized

Filename: Parse/ParseClient.php

Line Number: 240

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: Parse/ParseObject.php

Line Number: 618

Please help me to sold it!
Best Regards

**Comment by gfosco** [comment]
Heh.. what did you modify?  The error is saying the app id & rest key aren't valid.  This issue is unrelated, you should open your own issue in the future.

**Comment by buidinhnguyen** [comment]
I double check App ID & REST Api key are right.
I modified the _request method as: https://gist.github.com/allinora/c31ea781cb51da70c149
Also update http to https

Regards,

**Comment by gfosco** [comment]
What are you modifying it for?... What are you trying to accomplish?  Does it work without your modifications?

**Comment by gfosco** [comment]
I'm going to close this for now... very few affected cases, and we'll keep it in mind for future updates.
