### ISSUE TITLE
Allow ParseClient to accept pluggable transport layers

### ISSUE THREAD

**Issue by rinatkhaziev** [ParsePlatform/parse-php-sdk#59]
It would be nice to allow users to set different transport on a per use-case basis. 

Current implementation is final class ParseClient with request method relying on CURL. While curl is widely adopted, it might not be available due to platform restrictions/system setup (e.g. wordpress.com VIP does not allow usage of CURL: http://vip.wordpress.com/documentation/fetching-remote-data/#uncached-remote-requests). 

Nice approach to the problem can be found in Facebook's PHP SDK v4: 
https://github.com/facebook/facebook-php-sdk-v4/blob/4.0-dev/src/Facebook/FacebookRequest.php

FacebookRequest allows injection of various transports that implement FacebookHttpable interface, allowing developers to add custom transports that fit their needs. 

Cheers,
Rinat

**Comment by HipsterJazzbo** [comment]
@gfosco Doing a bit of grave digging: I'm finding curl to be intensely slow a lot of the time (like, up to twenty seconds to make a request). If I found time to jam Guzzle into the SDK instead, would that be acceptable? Or does it have to be something more like the Facebook SDK approach?

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
@HipsterJazzbo If it could be optional, that would be best.... but I'd consider it either way.

**Comment by montymxb** [comment]
#290 was recently added to integrate this functionality according to the way the [FB sdk](https://github.com/facebook/php-graph-sdk/blob/4.0-dev/src/Facebook/FacebookRequest.php) is designed. Currently there are two compatible clients, curl & stream, but further clients can be built and added by implementing the ```ParseHttpable``` interface.
