### ISSUE TITLE
Is the php SDK slower?

### ISSUE THREAD

**Issue by codeofRobin** [ParsePlatform/parse-php-sdk#67]
So, I was testing the PHP and JS SDK on a website, and it appears the php sdk takes 4-5 seconds more than the JS SDK. Any reason?

Here's my code:-
```php
<?php
require 'vendor/autoload.php';
 
use Parse\ParseClient;
 //removed my api keys

use Parse\ParseObject;
use Parse\ParseQuery;


$query=new ParseQuery("something");
try {
  $gameScore = $query->get("EYzG1jJs1g");
  // The object was retrieved successfully.
} catch (ParseException $ex) {
  // The object was not retrieved successfully.
  // error is a ParseException with an error code and message.
}
echo("\n");
echo($gameScore->get("name"));

$query=new ParseQuery("something");
try {
	$results=$query->find();
	echo "Successfully retrieved " . count($results) . " scores.";
	
	echo($results[3]->get("name"));

  // The object was retrieved successfully.
} catch (ParseException $ex) {
  // The object was not retrieved successfully.
  // error is a ParseException with an error code and message.
}
?>
```

And here's the JS code:-

```javascript
<script>

var TestObject = Parse.Object.extend("TestObject");
var testObject = new TestObject();
testObject.save({foo: "bar"}).then(function(object) {
  alert("yay! it worked");
});

var GameScore = Parse.Object.extend("something");
var query = new Parse.Query(GameScore);
query.get("vRNYbTWwuW", {
  success: function(gameScore) {
  
	alert(gameScore.get("name"));  	
    // The object was retrieved successfully.
  },
  error: function(object, error) {
    // The object was not retrieved successfully.
    // error is a Parse.Error with an error code and message.
  }
});
</script>
```

**Comment by gfosco** [comment]
How are you timing this?  The JS SDK is already loaded before it starts, and PHP comes with the server overhead of starting the PHP runtime.  It is not knowingly slower in practice.

**Comment by codeofRobin** [comment]
Sorry for the late reply. I'm timing these, well physically. Locally hosted files, MAMP running on the php SDK.

**Comment by gfosco** [comment]
I attribute the difference in time to your setup, and expect that the actual code execution is not slower if the environments could be excluded.  Feel free to instrument your code to try and isolate this.

**Comment by mithilesh2mik** [comment]
Hi, This is Mithilesh Kumar from New Delhi, India.
I am working on a product.
I have built a frontend to get data in our database.

As we have thousand rows of data,

let's say am fetching outlets which is 3000 in number right now.
outlets class has brand field which is pointer data type.

By, following code, it takes too much time.

Could you please suggest any optimized code it.????


use Parse\ParseObject;
use Parse\ParseQuery;
use Parse\ParseACL;
use Parse\ParsePush;
use Parse\ParseUser;
use Parse\ParseInstallation;
use Parse\ParseException;
use Parse\ParseAnalytics;
use Parse\ParseFile;
use Parse\ParseCloud;
use Parse\ParseClient;

ParseClient::initialize($appid, $rest_id , $master_key);



$query = new ParseQuery("Outlets");
$query->equalTo("status",(boolean)"true");
$query->limit(9999999999);
$results = $query->find();


           $brand_query = new ParseQuery("Brands");    // before loop
       
            for ($n = 0; $n < count($results); $n++) {
            $c_object = $results[$n];

                   $brand_query->equalTo("objectId",$c_object->get("brand")->getObjectId());
                   $brand_query_res = $brand_query->find();

                  echo $brand_query_res[0]->get('name');


          }

**Comment by gokbulut** [comment]
hi, php sdk really slow :(
