### ISSUE TITLE
Add connection timeout

### ISSUE THREAD

**Issue by jrmgx** [ParsePlatform/parse-php-sdk#70]
Something like
```php
    // Timeouts in seconds
    curl_setopt($rest, CURLOPT_CONNECTTIMEOUT, 10);
    curl_setopt($rest, CURLOPT_TIMEOUT, 10);
```

It will also need a specific error/exception

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Closing this due to age, but still open to reviewing a PR for this.
