### ISSUE TITLE
Insert Data Table 

### ISSUE THREAD

**Issue by fshafi** [ParsePlatform/parse-php-sdk#71]
Hi, i downloaded the sdk from here few days ago. There is an issue with inserting data into database server. Here is my code :+1: 

$object = new ParseObject("table");
$object->set("notes","test");

// Save:
$object->save();

during execution of this code it's showing below error :

"
Fatal error: Cannot use object of type __PHP_Incomplete_Class as array in C:\wamp\www\race-day-engineer-web\application\models\parseSDK\src\Parse\ParseUser.php on line 217
"

Thanks

**Comment by niraj-shah** [comment]
Try this instead:

```
$object = ParseObject::create("table");
$object->set("notes", "test");
$object->save();
```

**Comment by fshafi** [comment]
@niraj-shah : still not working

**Comment by fshafi** [comment]
$object = ParseObject::create("table");
$object->set("notes", "test");
$object->save();

**Comment by gfosco** [comment]
I think your error has nothing to do with this code, and everything to do with Sessions.  You need to require the Parse SDK before calling session_start();  If the SDK isn't loaded, it doesn't know how to unserialize the stored object.  Please re-open if this is not actually sessions related.
