### ISSUE TITLE
ParseClient.php line 259

### ISSUE THREAD

**Issue by nam-co** [ParsePlatform/parse-php-sdk#72]
Hi Gfosco, hope everything is ok, I need some guidance, I have an app that is sending/scheduling  like 200 pushes to parse early in the morning at the same time, just in case I added a usleep(100000); to make it wait after each push (so I don't exceed the 30 r/s parse limit) but Im getting an error:

ParseException in ParseClient.php line 259:
the request took too long to process

do you know how can I fix this?

Appreciate any help, regards

**Comment by gfosco** [comment]
Do you have this issue without the sleep?  You shouldn't need to sleep in this situation, as the burst limit is calculated at the minute level (1800 requests / minute).

If you do have the issue regardless, what are you sending in the push request?

**Comment by nam-co** [comment]
Thanks for the fat response, I took the unsell and it worked, but how can this be? isn't unsell just making a quick stop? strange (before it just send like 40 now it send all)

the data Im sending is: "channels" , "data" , "push_time"

**Comment by gfosco** [comment]
I don't have an answer there..  Where did you add the usleep?  I've written a large demo-data script and used sleep() between batches and it worked fine.
