### ISSUE TITLE
Add fetchAll: for batch fetching an array of objects

### ISSUE THREAD

**Issue by msmollin** [ParsePlatform/parse-php-sdk#75]
This would bring the PHP SDK in line with the other SDKs (iOS and Android are what I'm familiar with). I have an array of several hundred objects and I'd prefer not to have to loop through it and execute an individual fetch on each one.

**Comment by gfosco** [comment]
Any interest in submitting a PR for it?  That'll make it happen quicker.  You're right though, this should be added.  If you're not interested, I'll try to get to it soon.

**Comment by msmollin** [comment]
I'd have no problem attempting to do it. Should it be implemented similar to the destroyAll / saveAll methods?

**Comment by gfosco** [comment]
After looking at the implementations from JS and iOS, it's not as simple as I first expected.. 

Basically it collects the objectId's in a list and issues a regular Parse Query with the containedIn constraint.  After the query, it merges the results back into the provided object list (preserving outstanding operations, for example)..   We do have a mergeAfterFetch method, but not a method to handle the whole array.  If you want to attempt an implementation, I'll review it, but I don't expect you to.. I can take a look soon.

**Comment by msmollin** [comment]
Thanks! Yeah I have been wrapped up in my day job and other projects so been tough to even get to look at this.

**Comment by gfosco** [comment]
Submitted a PR for this #91
