### ISSUE TITLE
ParseQuery Regex Match

### ISSUE THREAD

**Issue by manuvendev** [ParsePlatform/parse-php-sdk#76]
Hi there!

Does anyone know if the PHP library  for ParseQuery allows regex matching? The JS library certainly does https://www.parse.com/docs/js/symbols/Parse.Query.html#matches and this would be a great enhancement.

Cheers!

**Comment by gfosco** [comment]
Regex constraints are discouraged, as they don't scale well..  The 'startsWith' constraint is okay, but the others may be deprecated at some point.  (see source for ParseQuery->startsWith function for how the regex constraints are constructed, if you wish to modify and use it on your own.)

**Comment by manuvendev** [comment]
Ok, thanks. 
But, in order to match some content on a column's value, if this cannot be done and you don't allow pure SQL queries... is there any other way to do this?. I am trying to find values containing a specific hashtag, and I don't see any function that will allow this. I am trying to avoid creating another table with the mapping.

**Comment by gfosco** [comment]
We have a blog post about tokenizing a field to make it easier to search, even using hashtags as an example:  http://blog.parse.com/2013/03/19/implementing-scalable-search-on-a-nosql-backend/

**Comment by acinader** [comment]
since the other language sdk's have this, so should php.  

for collections with 1-2m docs, this is very performant (for us anyway).

i can't re-open, but i'll submit a pr.

**Comment by acinader** [comment]
@montymxb you have any issue if i bring the sdk into parity with javascript? in this case by adding the missing contains function to Query.

**Comment by montymxb** [comment]
@acinader that seems fine to me. I just took a look at the JS implementation and you could base a ```ParseQuery::contains``` method off of ```ParseQuery::startsWith```. I'm not sure how this would fare in terms of performance on larger sets, but it makes sense to keep this in line with the other SDKs.

Just be sure to put in some test cases to account for the new functionality. If you put up a PR I can take a look at it as well, just to be sure we're not missing something.

**Comment by acinader** [comment]
👍 thanks @montymxb just getting my php ducks in a row here (been awhile) then i'll get that pr ready for you.
