### ISSUE TITLE
User sessions between browser quit and open

### ISSUE THREAD

**Issue by enricenrich** [ParsePlatform/parse-php-sdk#77]
Sorry for the title, but I wasn't able to explain better this problem. I have set up Parse PHP SDK on a web app, with the login working and logout too. The problem is that if I log in, then I close the browser and I open the web app, I'm not logged in.

I'm pretty sure that it's something very easy to implement, but I don't have much experience on PHP. I would love if you help me!

Thanks!

**Comment by gfosco** [comment]
Store the Parse User in the $_SESSION variable, so you can load it later.  Use PHP Sessions.  Require the Parse SDK and then start a session with: `session_start();`

When logging in:

```
try { 
  $user = ParseUser::logIn('login', 'password');
  $_SESSION['parseUser'] = $user;
} catch (ParseException $ex) {

}

```

When loading the page:
```
if (isset($_SESSION['parseUser'])) {
  $user = $_SESSION['parseUser'];
} else {
  // logged out... 
}
```

**Comment by enricenrich** [comment]
Doing it doesn't save the logged user between closing and opening the web browser, and also the computer. The same if I use `ParseClient::setStorage(new ParseSessionStorage());`.

Anyway, I found that if I do this:

```
$user = ParseUser::become($parseTwitterUser["sessionToken"]);
setcookie("ParseUserSession", $parseTwitterUser["sessionToken"], time()+31536000,'/');
header('Location: /');
```

It saves across browser sessions. Do you recommend me to save the session token of the user on a cookie? What do you recommend me to do to save the logged user session between browser and computer sessions?
