### ISSUE TITLE
Save Parse user session across browser sessions

### ISSUE THREAD

**Issue by enricenrich** [ParsePlatform/parse-php-sdk#78]
Hi,

I followed the steps mentioned on this issue (https://github.com/ParsePlatform/parse-php-sdk/issues/77), but it didn't work.

Doing it doesn't save the logged user between closing and opening the web browser, and also the computer. The same if I use `ParseClient::setStorage(new ParseSessionStorage());`.

Anyway, I found that if I do this:

```
$user = ParseUser::become($parseTwitterUser["sessionToken"]);
setcookie("ParseUserSession", $parseTwitterUser["sessionToken"], time()+31536000,'/');
header('Location: /');
```

It saves across browser sessions. Do you recommend me to save the session token of the user on a cookie? What do you recommend me to do to save the logged user session between browser and computer sessions?

**Comment by gfosco** [comment]
You should not be storing a session token in a cookie, as it can be read by the client (and potentially others.)  It's unclear how your code is set up, but if you're properly using sessions and storing/restoring the parse user, it should work.

**Comment by gfosco** [comment]
Additionally, I was wrong in #77.  We already do this.  See ParseClient, ParseSessionStorage, ParseStorageInterface.  If there's a PHP Session active, it will be persisted across page loads... If not, it will use memory storage and will be gone next page load.  You can write your own implementation of the ParseStorageInterface and use ParseClient::setStorage to use that.

**Comment by talkaboutdesign** [comment]
I have the same issue. Session stays active when the browser is open between multiple tabs. As soon as the browser is restarted the session is gone. Is there a sample you can point to on how to properly set this up.

**Comment by talkaboutdesign** [comment]
Session works across new tabs, etc. But as soon as browser is restarted its gone.

**Comment by adambarghouthi** [comment]
@talkaboutdesign have you figured this out?
