### ISSUE TITLE
PSR-2?

### ISSUE THREAD

**Issue by HipsterJazzbo** [ParsePlatform/parse-php-sdk#79]
Would you accept a PR converting this library to PSR-2?

**Comment by gfosco** [comment]
Yes, yes I would.

**Comment by GrahamCampbell** [comment]
https://styleci.io/ could be your friend there.

**Comment by HipsterJazzbo** [comment]
Awesome. It turns out to be a bit more work than I thought it'd be (PHPStorm doesn't do that good of a job), so I'll get to this when I can.

**Comment by GrahamCampbell** [comment]
> Awesome. It turns out to be a bit more work than I thought it'd be (PHPStorm doesn't do that good of a job), so I'll get to this when I can.

You can run this through styleci. It'll do the lot in a matter of seconds. You can can then download a diff you can apply using "git apply patch.txt", and you're done.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
PR at #80.

@GrahamCampbell, you are a wizard.

**Comment by HipsterJazzbo** [comment]
HOLY SCHMOLY GITHUB.
