### ISSUE TITLE
while login need to check the type of user

### ISSUE THREAD

**Issue by manojvelyalan** [ParsePlatform/parse-php-sdk#81]
Hi,

Now if i call log in function it is checking only the username and password.But i need to check the types of users. Only few types of users can log in in my system.How can i do this. Currently i am doing like this

     $user = Parse\ParseUser::logIn($_POST['email'], $_POST['password']);
        $currentUser = Parse\ParseUser::getCurrentUser();
        if($currentUser->accountType != "normal"){
             // redirect to another pager
        }else{
        Parse\ParseUser::logOut();
            $error[] = "We are sorry..You are not allow to login here.";
        }
   
The same thing i can solve if log in function can take another parameter account type.Then in the query itself i can check the account type , this will avoid one if else condition checking and unnecessary  one function call means log out function..

So we have any other way to solve this.Please advise me.

**Comment by gfosco** [comment]
This is an interesting use-case, but not something we can provide native assistance for.  You've implemented a reasonable workaround, given the situation.
