### ISSUE TITLE
Parse PHP SDK issue with unauthorized

### ISSUE THREAD

**Issue by buidinhnguyen** [ParsePlatform/parse-php-sdk#89]
Hi everyone,

When I config my site using CodeIgniter with Parse.
I had this issue:
PHP Fatal error:  Uncaught exception 'Parse\ParseException' with message 'unauthorized' in ... parse-php-sdk/src/Parse/ParseClient.php:292

I have set up with ParseClient::initialize().

Please give me some ideas to fix it.
Thank you so much!
Nguyen

**Comment by gfosco** [comment]
Where is ParseClient::initialize() being called?  I haven't used CodeIgniter..

**Comment by buidinhnguyen** [comment]
I called it in constructor of Controller.

**Comment by gfosco** [comment]
Found someone on StackOverflow working on the same issue, looks like he was able to make it work:  http://stackoverflow.com/a/29261090/353988
