### ISSUE TITLE
Parse Count Issue

### ISSUE THREAD

**Issue by dannewns** [ParsePlatform/parse-php-sdk#92]
Hi Team great work on the SDK, ive just got a slight issue with the count method on ParseQuery.

ive looked at the find method and the count method is there any particular reason you dont parse the session token along with the count method? im trying to run a quick count of the amount of records the logged in user has and of course they have some records that are private so its returning the incorrect result.

is there any other way apart from using find() to perform this kind of query as i dont really want to bring back all the data.

thanks

Dan

**Comment by gfosco** [comment]
This is a bug.  Nice find.  Will get this updated asap.

**Comment by gfosco** [comment]
Merged an update for this and tagged release version 1.1.1.  Let me know if you have any further issues.
