### ISSUE TITLE
Getting User data from a pointer

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/parse-php-sdk#94]
Hello, I got a ParseObject **Question** which contain filed **Autheur** as Pointer to **_User**.
 I want to get  First Name of user from the Question Object using the Autheur pointer , I've tried this : 
```
 $query = new ParseQuery("Question");
        $results = $query->find();
        foreach($results as $obj){
            echo $obj->get("Autheur")->get("firstName");
        }
```
But I got this error : 
```
ParseObject has no data for this key. Call fetch() to get the data.
 in ParseObject.php line 194
at ParseObject->get('firstName') in HomeController.php line 43
at HomeController->index()
``` 
How to Solve it ?

**Comment by gfosco** [comment]
Before you execute the query, use the includeKey method, to also retrieve the data for the pointed-to object:

```
$query = new ParseQuery("Question");
$query->includeKey("Autheur");
$results = $query->find();
foreach($results as $obj){
  echo $obj->get("Autheur")->get("firstName");
}
```

**Comment by chlebta** [comment]
Thank's a lot, and when I try to print the createdAt date I got an error like this : 
```
at HandleExceptions->handleError('2', 'htmlentities() expects parameter 1 to be string, object given', '/Applications/MAMP/htdocs/da3m/vendor/laravel/framework/src/Illuminate/Support/helpers.php', '455', array('value' => object(DateTime)))
```

**Comment by chlebta** [comment]
Thank's, Also in My Question Object I got column **Tags** that contains An array of pointer for Tags Object , this an example of the column content  : 
```
[{"__type":"Pointer","className":"Tags","objectId":"ZCXKRy8K5N"}] ``
```

So I tried This to display All tags for one question : 
```
$query = new ParseQuery("Question");
$query->includeKey("Tags");
$results = $query->find();
foreach($results as $obj){
  foreach($obj->get('Tags') as $tag){
echo $tag->get('Name');
}
}
```
But didn't worked How to solve it ? please

**Comment by gfosco** [comment]
Take a look at the response, var_dump($results);  If the column is indeed named Tags and it is an Array type column with pointers, they will be fetched as well.

**Comment by chlebta** [comment]
@gfosco  the Last issue I solved it but now i got another issue : I'have **Question** object that contain an array point to the different **Reponse** and each **Reponse** has also pointer to the **User** object, so I need to get the name of user foreach response so I tried this : 
```
$query = new ParseQuery("Question");
        $query->includeKey("Reponse");
//with this expresion
        $query->includeKey("Reponse")->includeKey("Autheur");
//and This expresion 
$query->includeKey("Autheur");
```
 Then  when I try to print the name of user related to response I get this : 
```
ParseObject has no data for this key ...
 ParseObject->get('displayName') 
```

When I try to dump the value ** {{dd($reponse->get('Autheur'))}}** I get this  : 
```
ParseUser {#174 ▼
  #_sessionToken: null
  #serverData: []
  #operationSet: []
  -estimatedData: []
  -dataAvailability: []
  -className: "_User"
  -objectId: "NrcLkAXMrj"
  -createdAt: null
  -updatedAt: null
  -hasBeenFetched: false
}
```
Which mean that my **Autheur** object hasn't been included 
How to solve this ?

**Comment by gfosco** [comment]
This will take care of that... remember to use column names.

```
$query->includeKey("Response");
$query->includeKey("Response.Autheur");
```

**Comment by jakeols** [comment]
I'm having a similar problem. I'm getting the error:

    Call to a member function get() on a non-object

My code is:

    $query = new ParseQuery("SignoutDestination");
       $query->includeKey("User");
       // Limit what could be a lot of points.
       $query->limit(100);
       // Final array of objects
       $signoutdestinations = $query->find();

       foreach($signoutdestinations as $obj){
         echo $obj->get("User")->get("objectId");
       }

Has there been a change in the SDK or anything that could be causing this?

**Comment by gfosco** [comment]
You should be checking the value of `$obj->get("User")` before attempting to access it.  Maybe you have objects without a user attached, or maybe "User" isn't the column name in "SignoutDestination"..

**Comment by jakeols** [comment]
I have, it returns the data (I'll attach a screenshot of the var_dump). I'm certain "User" is the column name in SignoutDestination, see below. 
![screen shot 2015-08-03 at 8 25 34 ptm](https://cloud.githubusercontent.com/assets/3232346/9050652/1408a4fa-3a1e-11e5-8f4e-e279333ee6ff.png)
![screen shot 2015-08-03 at 8 27 09 ptm](https://cloud.githubusercontent.com/assets/3232346/9050651/1407f924-3a1e-11e5-8da9-294700ad7959.png)

**Comment by gfosco** [comment]
Still don't see an issue or an error here.  Please troubleshoot your code, check for null objects along the way, and you'll figure this out.

**Comment by mzeeshan88** [comment]
hi im getting the same error Skip to main contentSkip to toolbar

Fatal error: Call to a member function get() on a non-object 

i have made plugin in that its not working only in one function but in all other function same code working absolutly fine .. 

bikeorder is a class and a pointer with named bike is added in query ..

$query = new ParseQuery('bikeorder');
	$query->includeKey("bike");
    $results = $query->find();
	
				foreach($results as $obj)
				{
					echo $obj->get("bike")->get("title");
				}

im strugling since 3 hours can anybody help on this please?

**Comment by montymxb** [comment]
Not too sure, but I would try debugging your code one step at a time, starting with ```$results```. If you're getting a an issue with a non-object something along the way is not as you expect it to be. 

See if you can't discern whether it's ```$obj->get("bike")``` or ```$obj->get("bike")->get("title")``` that's causing this fatal error. From there you should be able to start digging into the supposed non-object and figure out what's going on.

**Comment by jakeols** [comment]
@mzeeshan88 check to make sure bike/title isn't null for anything that you have stored. That ended up being my problem.
