### ISSUE TITLE
matches query in parse php

### ISSUE THREAD

**Issue by manojvelyalan** [ParsePlatform/parse-php-sdk#95]
Hi,

    I have two classes Request and _User.I want to match assignedUser field from Request  to _User.My code is below

public function getResponseList($currentUser,$email){

        $query = new \Parse\ParseQuery("Requests");
        $query->equalTo('assignedUser',$currentUser);
        $innerQuery = new \Parse\ParseQuery("_User");
         $innerQuery->equalTo('email', $email);
         $query->matchesQuery("assignedUser", $innerQuery);
        $query->descending("createdAt");
        $results = $query->find();       
        return $results;

    }

Fatal error: Cannot use object of type Parse\ParseUser as array in C:\xampp\htdocs\src\Parse\ParseQuery.php on line 103

**Comment by gfosco** [comment]
I'm not able to reproduce this issue... I set up a class, with a pointer column to User and the matchesQuery constraint worked fine.

Couple of things to note.  You can simplify your code by putting a use statement up top.. and your constraints look weird.  You're saying assignedUser must EQUAL the current user, and then asking it to also match another query.  This doesn't make sense.

Anyway, here's my test code which worked just fine:

```
<?php

date_default_timezone_set('UTC');

require('vendor/autoload.php');

use Parse\ParseClient;
use Parse\ParseObject;
use Parse\ParseQuery;
use Parse\ParseUser;

ParseClient::initialize("app-id","client-key", "master-key");

$query = new ParseQuery("osTest");
$innerQuery = ParseUser::query();
$innerQuery->equalTo("email", "abc@abc.com");
$query->matchesQuery("assignedUser", $innerQuery);
$results = $query->find(true);

var_dump($results);

```
