### ISSUE TITLE
matches query count issue 

### ISSUE THREAD

**Issue by manojvelyalan** [ParsePlatform/parse-php-sdk#96]
Hi
when I use the matches query in my query  the count of reccord is showign wrong. please find my  query below

public function TotalCount($subType) {
        $query = \Parse\ParseUser::query();
        $query->containedIn("accountType",["EU7VlXpVFz", "m3ZSohWwFj", "lTilWmTI4Y"]);     
	if($subType != "") {           
            $innerQuery = new \Parse\ParseQuery("General_Info");
            $innerQuery->equalTo('responderType', $subType);
            //$innerQuery->limit(1000000);
            $query->matchesQuery("responderInfo", $innerQuery);           
        }    
        $query->descending("createdAt");
        return $query->count();
    }
if am not setting the innerquery->limit manually it is giving the count only 100.The total reccord is more than hundred.

If am not setting the subtype it is giving me correct count.

**Comment by gfosco** [comment]
The query limit maxes out at 1000, even for inner queries.  Your count query will never return an accurate result.  You'll likely need to take another route to determine this result.

From our docs: https://parse.com/docs/php_guide#queries-counting

```
Caveat: Count queries are rate limited to a maximum of 160 requests per minute. They can also return inaccurate results for classes with more than 1,000 objects. Thus, it is preferable to architect your application to avoid this sort of count operation (by using counters, for example.)
```

**Comment by manojvelyalan** [comment]
You mean that there is no way to get the correct number of count if my total record more than 1000??

**Comment by gfosco** [comment]
You can retrieve all of the records, 1000 at a time, to get an accurate count.  To do that, I would order by objectId and page using a greaterThan constraint on the last objectId you've seen.  Or use the ->each method to process each record individually.

In many cases, the right approach is to keep counter columns, incrementing them and decrementing them as data changes.  It doesn't seem like that fits this type of query, though.

**Comment by manojvelyalan** [comment]
My ultimate aim is display all the record with pagination.For doing the
pagination i have to know the total count of the record, for getting the
page number.So please advise me how i can implement or where i can change
my code.

On Wed, Apr 22, 2015 at 10:52 AM, Fosco Marotto <notifications@github.com>
wrote:

> You can retrieve all of the records, 1000 at a time, to get an accurate
> count. To do that, I would order by objectId and page using a greaterThan
> constraint on the last objectId you've seen. Or use the ->each method to
> process each record individually.
>
> In many cases, the right approach is to keep counter columns, incrementing
> them and decrementing them as data changes. It doesn't seem like that fits
> this type of query, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-php-sdk/issues/96#issuecomment-95051980>
> .
>



-- 
Regards,
Manoj Velyalan
