### ISSUE TITLE
Parse LoginWithFacebook DateTime namespace issue

### ISSUE THREAD

**Issue by dannewns** [ParsePlatform/parse-php-sdk#97]
Hi Guys

first off once again great work on the SDK its really helping speed up dev, ive pulled down the latest version and tried to use the logInWithFacebook SDK and im getting the following error.

    Class 'Parse\DateTime' not found

ive looked at the method and can see on line 170 your instantiating a new DateTime object but because your under the Parse namespace for the class it cant find it DateTime class.

also you've created the loginWithFacebook method are you going to do the same for loginWithTwitter?

thanks

Dan

**Comment by dannewns** [comment]
so ive quickly just fixed this issue on my local setup to work through the rest of my code and when it performs the request there is another issue this time with the ParseClient

    ErrorException in ParseClient.php line 265:
    Array to string conversion

its a post method and ive taken a look at a few other other post methods in your classes and you json_encode the data array that you pass into it but it doesnt seem to be the case for this method.

**Comment by dannewns** [comment]
I've also spotted another issue with this method I hope its all ok to have it in this one ticket or should I open one for each one?

basically the old way of doing this via the rest API you would pass in a authDATA array containing an array for that social network i.e. facebook, twitter. this method doesnt do that, ive quickly modified the source method in my vendor folder to json_encode the data to get over the issue above but when i submit it it fails due to not having a password sent over but when i wrap the data in a authData key it works ok.

    $data = ["authData" => [ "facebook" => [
            "id" => $id, "access_token" => $access_token,
            "expiration_date" => ParseClient::getProperDateFormat($expiration_date)
        ]]];

im assuming the above would need to be done as well if you wanted to create a twitter login as well.

**Comment by gfosco** [comment]
Thanks for trying this... I hadn't tested it. :) I will take a look here and send a PR to address these.

**Comment by lhrasko** [comment]
I can verify the same issues discussed here. Also, the solutions offered by Dan did the trick for me.

**Comment by sherizan** [comment]
I'm also seeing the same issue "Fatal error: Class 'Parse\DateTime' not found in..."

parseUser = ParseUser::logInWithFacebook ($id, $token);

**Comment by dannewns** [comment]
hi @sherizan yes thats what i did to bypass it sorry about the delay in getting back in touch.

**Comment by gfosco** [comment]
Can one of you please submit a PR adding the \ to fix this?.. I meant to but have been busy and out of the office.

**Comment by gfosco** [comment]
Updated with #119

**Comment by gfosco** [comment]
In my haste to fix this yesterday I only covered 1 of 3 issues... Got them in there today with #123
