### ISSUE TITLE
Parse Intercept Exception Throw

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/parse-php-sdk#99]
Hello, when User type wrong userName or password it throw this exception ***ParseException in ParseClient.php line 293: invalid login parameters*** . my code looks like this : 
```
 try {
            return $this->user->logIn($this->getUsernameFromCredentials($credentials), $credentials['password']);
        } catch(ParseException $ex) {
            echo "Wroooong naaah";
        } 
```

Or when I try to get Object with invalid Id I get This error ***ParseException in ParseQuery.php line 93: Object not found.***  
So I need to know how to Intercept those Exception Message and print my Own or rediret to other page ( Note that Always I'm using try and catch but this doesn't help).

**Comment by gfosco** [comment]
Can you show more code?  What is 'user'?  Why not ParseUser::logIn()?

**Comment by chlebta** [comment]
I'm using Custom class that Extend ParseUser Login and Integrate it with Laravel Auth Systeme. Here's another snippet of code : 
```
$query = new ParseQuery("Reponse");
        try {
            $obj = $query->get($id);
            $obj->destroy();
            return Redirect::to('question/'. $id)->with('success', 'Successfully updated');
        } catch (ParseException $ex) {
            return Redirect::to('question/'. $id)->with('error', 'Opps try again please');
        }
```

When I try with invalid $id instead of execusting the catch block and this line.
 ```
return Redirect::to('question/'. $id)->with('error', 'Opps try again please');
```
It throw ParseExeption object not found

**Comment by gfosco** [comment]
At the top of that file, do you have a `use Parse\ParseException` reference?  Seems more like a PHP issue, the right exception isn't being caught.  If you changed your catch to catch everything (`catch (Exception $ex)`) does it work then?  Inspect the exception at that point.

Alternatively, have you seen: https://github.com/HipsterJazzbo/LaraParse

**Comment by chlebta** [comment]
Yeah I forgot to add `use Parse\ParseException`.
By the ways waht this exception means : **Parse::UserCannotBeAlteredWithoutSessionError** I get it when I try to updated Password : 
```
$user = Auth::user()->getParseUser();  //this will return ParseUser, the current User.
                $user->setPassword(Input::get('password'));
                $user->save();
```

**Comment by gfosco** [comment]
Is your 'current user' actually the ParseUser::getCurrentUser() ?  This error means that the session token was not set (user not logged in according to the SDK) and only the user can modify itself.
